-- ===== PART A: 새 카테고리 =====
INSERT INTO categories (id, name, slug, description, meta_description) VALUES
('c1000000-0000-0000-0000-000000000008', 'AI Productivity', 'ai-productivity', 'AI-powered productivity tools that help you work smarter, automate repetitive tasks, manage meetings, and optimize your time. From note-taking to scheduling, these tools transform how you work.', 'Best AI productivity tools in 2026. Compare features, pricing, and reviews for AI meeting assistants, note-takers, schedulers, and more.')
ON CONFLICT DO NOTHING;

-- ===== PART B: AI Coding Assistants 추가 (18개) =====
INSERT INTO ai_tools (name, slug, logo_url, website_url, short_description, long_description, category_id, pricing_model, starting_price, has_free_trial, affiliate_url, affiliate_program, commission_type, commission_rate, features, pros, cons, rating, monthly_visits, founded_year, meta_description, content_html) VALUES

(
  'Tabnine',
  'tabnine',
  'https://logo.clearbit.com/tabnine.com',
  'https://www.tabnine.com',
  'AI code completion tool that learns from your codebase and coding patterns to provide highly personalized suggestions.',
  'Tabnine is a pioneering AI coding assistant that uses deep learning to provide accurate code completions. Unlike cloud-only solutions, Tabnine offers both cloud and local on-device models, making it ideal for teams with strict data privacy requirements. It supports over 80 programming languages and integrates with all major IDEs.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  12.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"code_completion": true, "local_model": true, "team_learning": true, "80_plus_languages": true, "ide_integration": true, "private_deployment": true}',
  ARRAY['Strong privacy with local model option', 'Learns from your codebase', 'Supports 80+ languages', 'Works offline'],
  ARRAY['Less powerful than newer models', 'Free tier is limited', 'Slower than cloud-based alternatives'],
  7.8,
  2500000,
  2018,
  'Tabnine is an AI code completion tool supporting 80+ languages with local and cloud models. Privacy-first with team learning capabilities.',
  '<h2>What is Tabnine?</h2><p>Tabnine is one of the original AI coding assistants, providing intelligent code completions powered by deep learning. It uniquely offers both cloud-based and fully local on-device models, ensuring your code never leaves your machine when privacy is paramount.</p><h2>Key Features</h2><p>Tabnine supports over 80 programming languages and integrates seamlessly with popular IDEs including VS Code, IntelliJ, Vim, and more. Its team learning feature allows the AI to adapt to your team''s specific coding patterns and conventions.</p><h2>Pricing</h2><p>Tabnine offers a free tier with basic completions, and Pro plans starting at $12/month per user with full model access and team features.</p>'
),

(
  'Codeium',
  'codeium',
  'https://logo.clearbit.com/codeium.com',
  'https://codeium.com',
  'Free AI-powered code acceleration toolkit offering code completion, search, and chat for developers.',
  'Codeium provides free AI-powered code completion and chat capabilities for individual developers. Built on proprietary AI models trained on billions of lines of code, Codeium delivers fast, accurate suggestions across 70+ languages. It offers enterprise features including self-hosted deployment and SOC 2 compliance.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  0.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"free_forever": true, "70_plus_languages": true, "in_ide_chat": true, "code_search": true, "self_hosted": true, "soc2_compliant": true}',
  ARRAY['Completely free for individuals', 'Fast completion speed', 'Strong enterprise security options', 'Supports 70+ languages'],
  ARRAY['Enterprise pricing not transparent', 'Less context-aware than Copilot', 'Smaller community'],
  8.0,
  3200000,
  2022,
  'Codeium is a free AI code completion and chat tool supporting 70+ languages. Trusted by over 700,000 developers worldwide.',
  '<h2>What is Codeium?</h2><p>Codeium is an AI-powered code acceleration toolkit that is completely free for individual developers. It provides intelligent code completions, an in-IDE chat assistant, and powerful code search capabilities.</p><h2>Key Features</h2><p>Supporting over 70 programming languages and 40+ IDEs, Codeium offers some of the fastest code completions available. The in-editor chat allows you to ask questions, generate code, and refactor existing code without leaving your IDE.</p><h2>Pricing</h2><p>Codeium is free for individual developers with no usage limits. Enterprise plans with self-hosted deployment and advanced security features are available for teams.</p>'
),

(
  'Amazon CodeWhisperer',
  'amazon-codewhisperer',
  'https://logo.clearbit.com/aws.amazon.com',
  'https://aws.amazon.com/codewhisperer/',
  'Amazon''s AI coding companion that provides real-time code suggestions optimized for AWS services and cloud development.',
  'Amazon CodeWhisperer is AWS''s AI-powered coding assistant that helps developers write code faster and more securely. It provides real-time code suggestions trained on billions of lines of code, with special optimization for AWS APIs and services. It includes a built-in security scanner that identifies vulnerabilities aligned with OWASP top 10.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  0.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"aws_optimized": true, "security_scanning": true, "reference_tracking": true, "15_languages": true, "ide_integration": true, "free_individual_tier": true}',
  ARRAY['Free for individual use', 'Best-in-class AWS integration', 'Built-in security vulnerability scanning', 'License reference tracking'],
  ARRAY['Limited to 15 languages', 'Best for AWS-centric development', 'Less powerful outside AWS ecosystem'],
  7.5,
  1800000,
  2022,
  'Amazon CodeWhisperer is a free AI coding assistant optimized for AWS development with built-in security scanning. Perfect for cloud developers.',
  '<h2>What is Amazon CodeWhisperer?</h2><p>Amazon CodeWhisperer is AWS''s AI coding companion that provides real-time, AI-powered code suggestions directly in your IDE. It is trained on billions of lines of code and optimized specifically for AWS services and APIs.</p><h2>Key Features</h2><p>CodeWhisperer supports 15 programming languages and integrates with popular IDEs. Its unique security scanning feature automatically flags potential security vulnerabilities and suggests fixes based on OWASP top 10 and other security best practices.</p><h2>Pricing</h2><p>CodeWhisperer Individual is completely free with no usage limits. The Professional tier costs $19/user/month and adds administrative controls, SSO, and higher reference tracking limits.</p>'
),

(
  'Replit Ghostwriter',
  'replit-ghostwriter',
  'https://logo.clearbit.com/replit.com',
  'https://replit.com/ai',
  'AI coding assistant built into Replit''s online IDE, offering code completion, explanation, and generation in the browser.',
  'Replit Ghostwriter is an AI pair programmer deeply integrated into the Replit online development environment. It provides intelligent code completions, can explain complex code, transform code between languages, and generate entire functions from natural language descriptions. Ghostwriter Chat provides a conversational interface directly in the IDE.',
  'c1000000-0000-0000-0000-000000000003',
  'paid',
  20.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"in_browser_ide": true, "code_explanation": true, "code_transformation": true, "ghostwriter_chat": true, "multi_language": true, "instant_deployment": true}',
  ARRAY['Fully browser-based, no setup required', 'Instant deployment capabilities', 'Great for beginners and education', 'Tight IDE integration'],
  ARRAY['Requires Replit ecosystem', 'Not ideal for large enterprise projects', 'Higher pricing than alternatives'],
  7.2,
  9500000,
  2023,
  'Replit Ghostwriter is an AI pair programmer built into Replit''s browser IDE. Perfect for rapid prototyping and learning to code with AI assistance.',
  '<h2>What is Replit Ghostwriter?</h2><p>Replit Ghostwriter is an AI pair programmer built directly into the Replit online IDE. It offers a seamless coding experience with AI assistance accessible entirely through your web browser, requiring no local setup or configuration.</p><h2>Key Features</h2><p>Ghostwriter provides real-time code completion, can explain code in plain English, transform code between programming languages, and generate functions from natural language. The integrated Ghostwriter Chat allows you to have a conversation with AI about your code.</p><h2>Pricing</h2><p>Ghostwriter is available as part of Replit''s Core plan at $20/month, which also includes additional compute resources and storage for your projects.</p>'
),

(
  'Sourcegraph Cody',
  'sourcegraph-cody',
  'https://logo.clearbit.com/sourcegraph.com',
  'https://sourcegraph.com/cody',
  'AI coding assistant with deep codebase context, using your entire repository to provide highly accurate suggestions.',
  'Sourcegraph Cody is a powerful AI coding assistant that stands out by using your entire codebase as context. Unlike other tools that only see your current file, Cody can search across your whole repository to provide accurate, context-aware suggestions. It supports multiple LLM backends including Claude, GPT-4, and open-source models.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  9.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"full_codebase_context": true, "multi_llm_support": true, "code_search": true, "enterprise_ready": true, "vs_code_extension": true, "self_hosted_option": true}',
  ARRAY['Uses entire codebase for context', 'Supports multiple LLM backends', 'Enterprise-grade security', 'Powerful code search'],
  ARRAY['More complex setup than competitors', 'Best features require Pro plan', 'Heavier resource usage'],
  8.1,
  1200000,
  2023,
  'Sourcegraph Cody is an AI coding assistant that uses your entire codebase as context for accurate suggestions. Supports Claude, GPT-4, and more.',
  '<h2>What is Sourcegraph Cody?</h2><p>Sourcegraph Cody is an AI coding assistant that leverages Sourcegraph''s powerful code intelligence platform to provide context-aware assistance across your entire codebase. Unlike assistants limited to the current file, Cody can search and understand your full repository.</p><h2>Key Features</h2><p>Cody supports multiple AI models including Anthropic Claude and OpenAI GPT-4, giving teams flexibility in choosing their preferred LLM. It offers code completion, an AI chat interface, and can perform complex refactoring tasks with full codebase awareness.</p><h2>Pricing</h2><p>Cody Free offers basic code completion and chat. Cody Pro at $9/month unlocks unlimited usage and priority access to the most powerful models.</p>'
),

(
  'Windsurf AI',
  'windsurf-ai',
  'https://logo.clearbit.com/codeium.com',
  'https://windsurf.com',
  'Agentic AI IDE by Codeium that combines deep contextual awareness with autonomous coding capabilities.',
  'Windsurf is an agentic AI-powered IDE developed by Codeium. It goes beyond simple code completion to offer autonomous coding flows where the AI can understand your intent, plan multi-step changes, and execute them across your entire codebase. The Cascade feature allows the AI to take actions, run commands, and iterate based on results.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  15.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"agentic_flows": true, "cascade_feature": true, "full_ide": true, "terminal_integration": true, "multi_file_editing": true, "context_engine": true}',
  ARRAY['True agentic AI coding capabilities', 'Full IDE with deep AI integration', 'Can execute terminal commands', 'Strong free tier'],
  ARRAY['Newer product, still maturing', 'Requires learning new IDE', 'Some instability reported'],
  8.3,
  2800000,
  2024,
  'Windsurf is an agentic AI IDE by Codeium featuring Cascade for autonomous multi-step coding tasks. The next evolution in AI-assisted development.',
  '<h2>What is Windsurf AI?</h2><p>Windsurf is an agentic AI-powered IDE created by Codeium that takes AI-assisted coding to the next level. Instead of just completing code, Windsurf''s Cascade feature can understand your high-level intent and autonomously execute multi-step coding tasks.</p><h2>Key Features</h2><p>The flagship Cascade feature allows Windsurf to take actions, write code across multiple files, run terminal commands, browse documentation, and iterate based on feedback — all autonomously. It maintains deep context awareness of your entire codebase.</p><h2>Pricing</h2><p>Windsurf offers a free tier with generous usage limits. Pro plans start at $15/month for unlimited AI interactions and access to the most powerful models.</p>'
),

(
  'Claude Code',
  'claude-code',
  'https://logo.clearbit.com/anthropic.com',
  'https://claude.ai/code',
  'Anthropic''s agentic coding tool that operates in your terminal, capable of understanding and modifying entire codebases.',
  'Claude Code is Anthropic''s agentic coding CLI tool powered by Claude. It operates directly in your terminal and can read, write, and modify files across your entire codebase. Claude Code can execute shell commands, run tests, manage git operations, and autonomously complete complex multi-step development tasks with minimal human intervention.',
  'c1000000-0000-0000-0000-000000000003',
  'paid',
  20.00,
  FALSE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"agentic_coding": true, "terminal_based": true, "git_integration": true, "full_codebase_access": true, "test_execution": true, "multi_step_tasks": true}',
  ARRAY['Extremely powerful agentic capabilities', 'Full codebase understanding', 'Executes real terminal commands', 'Best-in-class reasoning for code'],
  ARRAY['Requires API subscription', 'Can be expensive for heavy use', 'Terminal-based only (no GUI)'],
  9.0,
  4500000,
  2025,
  'Claude Code is Anthropic''s agentic coding CLI that autonomously reads, writes, and executes code across your entire codebase from the terminal.',
  '<h2>What is Claude Code?</h2><p>Claude Code is Anthropic''s official agentic coding tool that runs in your terminal. Powered by Claude, it can autonomously understand your entire codebase, write and modify files, execute shell commands, run tests, and complete complex development tasks end-to-end.</p><h2>Key Features</h2><p>Claude Code offers true agentic capabilities — it can read all your files, make changes across multiple files simultaneously, commit to git, run your test suite, and iterate until tasks are complete. It understands context at a project-wide level rather than just the current file.</p><h2>Pricing</h2><p>Claude Code is available through Anthropic''s API with usage-based pricing. Claude Pro subscribers get access with included usage, and additional usage is billed per token consumed.</p>'
),

(
  'Aider',
  'aider',
  'https://logo.clearbit.com/aider.chat',
  'https://aider.chat',
  'Open-source AI pair programming in your terminal that works with multiple LLMs to edit code in your local git repository.',
  'Aider is an open-source AI pair programming tool that runs in your terminal and integrates with your local git repository. It works with multiple LLMs including Claude, GPT-4, and others, allowing you to have conversations with AI to write and edit code. Aider automatically commits changes to git with descriptive messages.',
  'c1000000-0000-0000-0000-000000000003',
  'free',
  0.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"open_source": true, "git_integration": true, "multi_llm": true, "terminal_based": true, "auto_commits": true, "map_whole_repo": true}',
  ARRAY['Completely free and open source', 'Works with any LLM', 'Automatic git commits', 'Strong community support'],
  ARRAY['Requires LLM API keys (paid separately)', 'Terminal-only interface', 'Steeper learning curve'],
  8.2,
  850000,
  2023,
  'Aider is a free open-source AI pair programmer that runs in your terminal, integrates with git, and works with Claude, GPT-4, and other LLMs.',
  '<h2>What is Aider?</h2><p>Aider is a free, open-source AI pair programming tool that runs in your terminal. It connects to your preferred LLM (Claude, GPT-4, Gemini, and more) to help you write and edit code in your local git repository through natural language conversations.</p><h2>Key Features</h2><p>Aider creates a repository map to understand your entire codebase, allows multi-file edits in a single conversation, and automatically creates git commits with descriptive messages for every change. It supports over 50 programming languages and works with any git repository.</p><h2>Pricing</h2><p>Aider itself is completely free and open source. You only pay for the LLM API you choose to use (OpenAI, Anthropic, Google, etc.).</p>'
),

(
  'Continue.dev',
  'continue-dev',
  'https://logo.clearbit.com/continue.dev',
  'https://continue.dev',
  'Open-source AI code assistant that allows you to connect any LLM to your VS Code or JetBrains IDE.',
  'Continue is an open-source AI code assistant that gives developers full control over their AI coding experience. It integrates with VS Code and JetBrains IDEs and allows you to connect any LLM — whether cloud-based (Claude, GPT-4, Gemini) or locally running (Ollama, LM Studio). Continue supports autocomplete, chat, and edit workflows.',
  'c1000000-0000-0000-0000-000000000003',
  'free',
  0.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"open_source": true, "any_llm_support": true, "local_llm": true, "vs_code": true, "jetbrains": true, "customizable": true}',
  ARRAY['Fully open source and free', 'Connect any LLM including local models', 'Highly customizable', 'Active development community'],
  ARRAY['Requires LLM API configuration', 'Less polished than commercial tools', 'Documentation can be lacking'],
  8.0,
  680000,
  2023,
  'Continue.dev is a free open-source AI coding assistant for VS Code and JetBrains that supports any LLM including local models like Ollama.',
  '<h2>What is Continue.dev?</h2><p>Continue is an open-source AI code assistant that gives you complete freedom in choosing and configuring your AI models. Unlike proprietary tools, Continue lets you connect to any LLM — from cloud providers like Anthropic and OpenAI to locally running models via Ollama.</p><h2>Key Features</h2><p>Continue integrates with VS Code and JetBrains IDEs offering tab autocomplete, an AI chat interface, and inline edit capabilities. You can customize prompts, context providers, and model configurations to build the perfect AI coding environment for your needs.</p><h2>Pricing</h2><p>Continue is completely free and open source. You only pay for whatever LLM API you choose to connect, or use it for free with local models via Ollama.</p>'
),

(
  'Cline',
  'cline',
  'https://logo.clearbit.com/github.com',
  'https://github.com/cline/cline',
  'Open-source autonomous AI coding agent for VS Code that can create and edit files, execute commands, and browse the web.',
  'Cline (formerly Claude Dev) is an open-source autonomous coding agent that runs as a VS Code extension. It can create and edit files, execute terminal commands, search the web, and use browser automation to complete complex development tasks. Cline works with multiple LLMs and shows every action it takes for full transparency.',
  'c1000000-0000-0000-0000-000000000003',
  'free',
  0.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"autonomous_agent": true, "vs_code_extension": true, "browser_automation": true, "terminal_commands": true, "multi_llm": true, "transparent_actions": true}',
  ARRAY['Fully autonomous agent capabilities', 'Complete transparency of actions', 'Free and open source', 'Browser use capability'],
  ARRAY['Requires LLM API keys', 'Can be expensive with heavy LLM use', 'Newer tool, still evolving'],
  8.4,
  920000,
  2024,
  'Cline is a free open-source autonomous AI coding agent for VS Code that creates files, runs commands, and browses the web to complete dev tasks.',
  '<h2>What is Cline?</h2><p>Cline is an open-source autonomous AI coding agent that operates as a VS Code extension. It takes AI-assisted coding further by acting as a fully autonomous agent that can plan and execute complex development tasks with minimal human intervention.</p><h2>Key Features</h2><p>Cline can read and write files across your project, execute terminal commands, browse the web for documentation, and even use browser automation to test web apps. Every action is shown to the user for approval, maintaining full transparency and control.</p><h2>Pricing</h2><p>Cline itself is completely free. Costs come from LLM API usage — it works with Claude, GPT-4, Gemini, and other providers, or local models via Ollama.</p>'
),

(
  'v0 by Vercel',
  'v0-vercel',
  'https://logo.clearbit.com/vercel.com',
  'https://v0.dev',
  'Vercel''s AI-powered UI generation tool that creates React components and full interfaces from natural language descriptions.',
  'v0 is Vercel''s generative UI tool powered by AI that creates production-ready React and Next.js components from text descriptions and screenshots. It uses shadcn/ui and Tailwind CSS by default and generates clean, accessible code that can be directly integrated into your projects. v0 understands design intent and creates functional UI components.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  20.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"ui_generation": true, "react_components": true, "nextjs_optimized": true, "shadcn_ui": true, "tailwind_css": true, "screenshot_to_code": true}',
  ARRAY['Excellent UI generation quality', 'Tight Next.js and Vercel integration', 'Production-ready code output', 'Screenshot to code feature'],
  ARRAY['Focused on React/Next.js ecosystem', 'Free tier has limited credits', 'Less useful for backend code'],
  8.5,
  5500000,
  2023,
  'v0 by Vercel is an AI UI generation tool that creates production-ready React components from text descriptions. Built on shadcn/ui and Tailwind CSS.',
  '<h2>What is v0 by Vercel?</h2><p>v0 is Vercel''s AI-powered UI generation platform that transforms text descriptions and screenshots into production-ready React components. It generates clean, modern UI using shadcn/ui components and Tailwind CSS, making it a go-to tool for rapid frontend development.</p><h2>Key Features</h2><p>Simply describe the UI you want in natural language, or upload a screenshot, and v0 generates the corresponding React code. The output is clean, accessible, and immediately usable in Next.js or React projects. You can iterate on designs through conversation.</p><h2>Pricing</h2><p>v0 offers a free tier with limited monthly credits. Premium plans starting at $20/month provide more generations and access to advanced features including full Next.js app generation.</p>'
),

(
  'Bolt.new',
  'bolt-new',
  'https://logo.clearbit.com/bolt.new',
  'https://bolt.new',
  'StackBlitz''s AI-powered full-stack web development tool that builds, runs, and deploys complete web applications in the browser.',
  'Bolt.new is an AI-powered web development agent by StackBlitz that enables building complete full-stack applications directly in the browser. Powered by Claude, it can install packages, run servers, and create entire applications from a single prompt. Bolt runs a full Node.js environment in the browser using WebContainers technology.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  20.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"full_stack_generation": true, "browser_based": true, "webcontainers": true, "npm_support": true, "instant_deployment": true, "no_setup": true}',
  ARRAY['Build full-stack apps in browser', 'No local setup required', 'Instant preview and deployment', 'Supports npm packages'],
  ARRAY['Limited compute resources on free tier', 'Better for prototypes than production', 'Can struggle with complex architectures'],
  8.4,
  7200000,
  2024,
  'Bolt.new by StackBlitz is an AI web development agent that builds complete full-stack applications in your browser. Powered by Claude AI.',
  '<h2>What is Bolt.new?</h2><p>Bolt.new is an AI-powered web development agent created by StackBlitz that allows you to build, run, and deploy complete web applications entirely in your browser. Using StackBlitz''s WebContainers technology and powered by Claude AI, it creates fully functional apps from natural language prompts.</p><h2>Key Features</h2><p>Bolt.new can generate complete full-stack applications with React, Vue, Node.js, and more — including package installation, server configuration, and database setup. Everything runs in the browser with no local installation required, and apps can be deployed with a single click.</p><h2>Pricing</h2><p>Bolt.new offers a free tier with daily token limits. Pro plans start at $20/month for higher usage limits and access to more powerful AI models.</p>'
),

(
  'Lovable AI',
  'lovable-ai',
  'https://logo.clearbit.com/lovable.dev',
  'https://lovable.dev',
  'AI software engineer that builds full-stack web applications from natural language, with GitHub sync and Supabase integration.',
  'Lovable (formerly GPT Engineer App) is an AI full-stack software engineer that builds complete web applications from natural language descriptions. It generates production-ready React applications with Supabase backends, syncs to GitHub, and allows real-time collaboration. Lovable is designed to make software development accessible to non-developers.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  25.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"full_stack_apps": true, "supabase_integration": true, "github_sync": true, "react_generation": true, "real_time_preview": true, "custom_domains": true}',
  ARRAY['Excellent Supabase integration', 'GitHub sync for version control', 'No-code to full-stack apps', 'Custom domain support'],
  ARRAY['Can require manual fixes for complex apps', 'Free tier has limited messages', 'Less control than code-first tools'],
  8.3,
  4800000,
  2024,
  'Lovable AI is an AI software engineer that builds complete full-stack React apps with Supabase backends from natural language. GitHub sync included.',
  '<h2>What is Lovable AI?</h2><p>Lovable is an AI-powered software engineer that transforms natural language descriptions into complete full-stack web applications. Built for both developers and non-developers, it generates production-ready React frontends with Supabase backends.</p><h2>Key Features</h2><p>Lovable features seamless Supabase integration for databases, authentication, and storage, along with GitHub synchronization for version control. It offers a real-time preview, custom domain support, and the ability to iterate on your application through natural language conversation.</p><h2>Pricing</h2><p>Lovable offers a free tier with limited monthly messages. Pro plans start at $25/month for increased usage, and teams can access higher limits with business plans.</p>'
),

(
  'Devin AI',
  'devin-ai',
  'https://logo.clearbit.com/cognition.ai',
  'https://devin.ai',
  'World''s first fully autonomous AI software engineer capable of completing end-to-end software engineering tasks independently.',
  'Devin is the world''s first AI software engineer developed by Cognition AI. It operates as a fully autonomous agent with its own shell, code editor, and browser. Devin can plan and execute long-horizon engineering tasks, fix bugs, build features, and even learn new technologies from documentation — all with minimal human oversight.',
  'c1000000-0000-0000-0000-000000000003',
  'paid',
  500.00,
  FALSE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"fully_autonomous": true, "own_environment": true, "long_horizon_tasks": true, "bug_fixing": true, "documentation_learning": true, "swe_bench_leading": true}',
  ARRAY['Most autonomous AI engineer available', 'Can handle entire engineering workflows', 'Learns from documentation', 'Leading SWE-bench scores'],
  ARRAY['Very expensive pricing', 'Not suitable for all team workflows', 'Can make mistakes requiring review'],
  8.0,
  1500000,
  2024,
  'Devin is the world''s first fully autonomous AI software engineer by Cognition AI. Capable of completing end-to-end engineering tasks independently.',
  '<h2>What is Devin AI?</h2><p>Devin is the world''s first fully autonomous AI software engineer, developed by Cognition AI. Unlike AI coding assistants that help humans write code, Devin operates independently as a software engineer — planning, coding, testing, and deploying solutions with minimal human oversight.</p><h2>Key Features</h2><p>Devin has its own sandboxed environment complete with a code editor, terminal, and browser. It can tackle complex engineering tasks that span hours of work, research and learn new technologies from documentation, fix bugs in large codebases, and contribute to real open-source projects.</p><h2>Pricing</h2><p>Devin is available through enterprise agreements with Cognition AI. Pricing is based on usage and team size, typically starting at hundreds of dollars per month for team access.</p>'
),

(
  'Sweep AI',
  'sweep-ai',
  'https://logo.clearbit.com/sweep.dev',
  'https://sweep.dev',
  'AI junior developer that converts GitHub issues and comments into pull requests automatically.',
  'Sweep is an AI-powered junior developer that lives in your GitHub repository. When you create an issue or comment "@sweep" on a GitHub issue, Sweep autonomously plans the changes, writes the code, runs tests, and opens a pull request. It handles bug fixes, small features, and code refactoring tasks directly in GitHub.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  19.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"github_native": true, "auto_pr_creation": true, "issue_to_code": true, "test_generation": true, "code_review": true, "open_source": true}',
  ARRAY['Native GitHub integration', 'Automatic PR creation from issues', 'Generates tests automatically', 'Open source version available'],
  ARRAY['Limited to GitHub workflow', 'Can struggle with complex changes', 'Requires issue to be well-defined'],
  7.3,
  320000,
  2023,
  'Sweep AI automatically converts GitHub issues into pull requests. An AI junior developer that plans, codes, and submits PRs from natural language issues.',
  '<h2>What is Sweep AI?</h2><p>Sweep is an AI junior developer that integrates directly into your GitHub workflow. Simply create a GitHub issue describing what you want built or fixed, and Sweep autonomously plans the implementation, writes the code, runs your tests, and opens a pull request for review.</p><h2>Key Features</h2><p>Sweep understands your entire codebase context and can handle bug fixes, small feature additions, and refactoring tasks. It generates tests for the code it writes and provides detailed comments explaining its changes, making code review straightforward.</p><h2>Pricing</h2><p>Sweep offers a free tier for public repositories and open-source projects. Pro plans at $19/month support private repositories with higher usage limits.</p>'
),

(
  'OpenAI Codex',
  'codex-openai',
  'https://logo.clearbit.com/openai.com',
  'https://openai.com/blog/openai-codex',
  'OpenAI''s AI system that translates natural language to code, powering GitHub Copilot and available via API.',
  'OpenAI Codex is the AI system that translates natural language to code and served as the foundation for GitHub Copilot. Trained on billions of lines of public code, Codex is proficient in over a dozen programming languages. It is accessible via the OpenAI API for developers building code generation tools and applications.',
  'c1000000-0000-0000-0000-000000000003',
  'paid',
  0.03,
  FALSE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"natural_language_to_code": true, "api_access": true, "12_plus_languages": true, "docstring_generation": true, "code_explanation": true, "powers_copilot": true}',
  ARRAY['Foundation of GitHub Copilot', 'Powerful API for building tools', 'Excels at Python and JavaScript', 'Strong documentation generation'],
  ARRAY['API-only access', 'Newer models have superseded it', 'Requires development to build on top of'],
  7.0,
  2100000,
  2021,
  'OpenAI Codex translates natural language to code and powers GitHub Copilot. Available via API for building custom code generation applications.',
  '<h2>What is OpenAI Codex?</h2><p>OpenAI Codex is the AI model that translates natural language descriptions into working code. It was the driving technology behind GitHub Copilot and represented a major breakthrough in AI-assisted software development when released in 2021.</p><h2>Key Features</h2><p>Codex is proficient in over a dozen programming languages with particular strength in Python, JavaScript, Go, Perl, PHP, Ruby, Swift, and TypeScript. Accessible via the OpenAI API, developers can use it to build their own code generation tools, documentation systems, and coding education platforms.</p><h2>Pricing</h2><p>Codex is accessible through the OpenAI API with usage-based pricing per token. Note that OpenAI''s newer GPT-4o and o3 models have largely superseded Codex for most code generation use cases.</p>'
),

(
  'StarCoder',
  'starcoder',
  'https://logo.clearbit.com/huggingface.co',
  'https://huggingface.co/bigcode/starcoder2-15b',
  'Open-source large language model for code, trained on permissively licensed data from GitHub by BigCode and HuggingFace.',
  'StarCoder is a family of open-source large language models for code developed by BigCode, a collaboration between HuggingFace and ServiceNow. Trained on permissively licensed code from GitHub covering 80+ programming languages, StarCoder2 models are available in 3B, 7B, and 15B parameter sizes. They can be run locally or self-hosted.',
  'c1000000-0000-0000-0000-000000000003',
  'free',
  0.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"open_source": true, "80_plus_languages": true, "self_hostable": true, "multiple_sizes": true, "permissive_license": true, "fill_in_middle": true}',
  ARRAY['Completely open source and free', 'Self-hostable for privacy', 'Multiple model sizes available', 'Permissive licensing'],
  ARRAY['Requires technical setup to self-host', 'Less capable than GPT-4 based tools', 'No built-in IDE integration'],
  7.4,
  480000,
  2023,
  'StarCoder is a free open-source code LLM by BigCode and HuggingFace. Supports 80+ languages and can be self-hosted for complete privacy.',
  '<h2>What is StarCoder?</h2><p>StarCoder is a family of open-source large language models for code generation, developed by BigCode — a collaboration between HuggingFace and ServiceNow. It offers a fully open-source alternative to proprietary coding models.</p><h2>Key Features</h2><p>StarCoder2 models are available in sizes from 1.3B to 33B parameters and support over 80 programming languages. They feature fill-in-the-middle capabilities for code completion and were trained exclusively on permissively licensed code, making them safe for commercial use.</p><h2>Pricing</h2><p>StarCoder is completely free and open source. You can run it locally using tools like Ollama, self-host it on your own servers, or access it for free via the HuggingFace Inference API.</p>'
),

(
  'DeepSeek Coder',
  'deepseek-coder',
  'https://logo.clearbit.com/deepseek.com',
  'https://coder.deepseek.com',
  'High-performance open-source code generation model from DeepSeek that rivals GPT-4 at a fraction of the cost.',
  'DeepSeek Coder is a series of code-specialized large language models developed by DeepSeek AI. The models range from 1.3B to 33B parameters and have demonstrated state-of-the-art performance on coding benchmarks. Available as open-source models and through an affordable API, DeepSeek Coder supports 338 programming languages.',
  'c1000000-0000-0000-0000-000000000003',
  'freemium',
  0.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"338_languages": true, "open_source": true, "api_access": true, "multiple_sizes": true, "fill_in_middle": true, "instruction_following": true}',
  ARRAY['Excellent performance-to-cost ratio', 'Supports 338 programming languages', 'Open source models available', 'Very affordable API pricing'],
  ARRAY['Data privacy concerns for some enterprises', 'Server location outside US/EU', 'Less established than OpenAI/Anthropic'],
  8.2,
  6800000,
  2024,
  'DeepSeek Coder is a high-performance open-source code AI supporting 338 languages. Rivals GPT-4 on coding benchmarks at significantly lower cost.',
  '<h2>What is DeepSeek Coder?</h2><p>DeepSeek Coder is a series of code-specialized AI models developed by DeepSeek AI that have achieved remarkable performance on coding benchmarks, often matching or exceeding GPT-4 at a fraction of the cost. Available as both open-source models and via API.</p><h2>Key Features</h2><p>DeepSeek Coder models are available in sizes from 1.3B to 33B parameters and support an impressive 338 programming languages. They excel at code completion, generation, and explanation tasks. The instruction-tuned variants handle complex coding requests effectively.</p><h2>Pricing</h2><p>DeepSeek Coder models are open source and free to self-host. The DeepSeek API offers very competitive pricing, typically 5-10x cheaper than comparable OpenAI API calls, making it cost-effective for high-volume applications.</p>'
)

ON CONFLICT (slug) DO NOTHING;

-- ===== PART C: AI Productivity (15개) =====
INSERT INTO ai_tools (name, slug, logo_url, website_url, short_description, long_description, category_id, pricing_model, starting_price, has_free_trial, affiliate_url, affiliate_program, commission_type, commission_rate, features, pros, cons, rating, monthly_visits, founded_year, meta_description, content_html) VALUES

(
  'Notion AI',
  'notion-ai',
  'https://logo.clearbit.com/notion.so',
  'https://www.notion.so/product/ai',
  'AI writing and productivity assistant built into Notion that helps you write, summarize, translate, and analyze content.',
  'Notion AI is an integrated AI assistant built directly into the Notion workspace. It helps teams and individuals write better content, summarize long documents, translate text into multiple languages, extract action items from meeting notes, and generate structured content like tables and timelines. Notion AI understands your workspace context.',
  'c1000000-0000-0000-0000-000000000008',
  'paid',
  10.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"writing_assistance": true, "summarization": true, "translation": true, "action_item_extraction": true, "q_and_a": true, "autofill_tables": true}',
  ARRAY['Deeply integrated into Notion workflow', 'Understands your workspace context', 'Excellent summarization capabilities', 'Easy to use for non-technical users'],
  ARRAY['Requires Notion subscription', 'Add-on cost on top of existing plan', 'Less powerful than standalone AI tools'],
  8.2,
  45000000,
  2023,
  'Notion AI adds AI writing, summarization, and analysis directly into your Notion workspace. Write faster, extract insights, and automate tasks.',
  '<h2>What is Notion AI?</h2><p>Notion AI is an AI-powered assistant built directly into the Notion productivity platform. It enhances your existing Notion workflow by adding intelligent writing assistance, content summarization, and information extraction capabilities without leaving your workspace.</p><h2>Key Features</h2><p>Notion AI can write and improve text, summarize long documents, translate content into 10+ languages, extract action items and key points from meeting notes, and autofill database properties. The Q&A feature lets you ask questions about your entire Notion workspace.</p><h2>Pricing</h2><p>Notion AI is available as an add-on to any Notion plan for $10/user/month (or $8/month billed annually). It requires an existing Notion workspace subscription.</p>'
),

(
  'Otter.ai',
  'otter-ai',
  'https://logo.clearbit.com/otter.ai',
  'https://otter.ai',
  'AI meeting assistant that provides real-time transcription, automated meeting summaries, and action item extraction.',
  'Otter.ai is a leading AI-powered meeting assistant that automatically transcribes meetings in real time. It integrates with Zoom, Google Meet, and Microsoft Teams to capture everything said, generate comprehensive summaries, and extract action items. Otter''s AI can answer questions about past meetings and provides searchable transcripts.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  16.99,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"real_time_transcription": true, "meeting_summaries": true, "action_items": true, "zoom_integration": true, "google_meet": true, "ms_teams": true}',
  ARRAY['Industry-leading transcription accuracy', 'Real-time transcription during meetings', 'Integrates with all major video platforms', 'Searchable meeting history'],
  ARRAY['Free tier has limited monthly minutes', 'Can struggle with heavy accents', 'Requires meeting platform integration'],
  8.3,
  8200000,
  2016,
  'Otter.ai provides real-time AI meeting transcription, automated summaries, and action item extraction for Zoom, Meet, and Teams meetings.',
  '<h2>What is Otter.ai?</h2><p>Otter.ai is an AI meeting assistant that transforms how teams capture and utilize meeting information. It automatically joins your video calls and provides real-time transcription, making it easy to stay present in meetings without manual note-taking.</p><h2>Key Features</h2><p>Otter integrates with Zoom, Google Meet, Microsoft Teams, and Webex to automatically transcribe meetings. After each meeting, it generates an AI summary with key points and action items. The Otter AI Chat allows you to ask questions about past meetings and retrieve specific information.</p><h2>Pricing</h2><p>Otter offers a free plan with 300 monthly transcription minutes. Pro plans start at $16.99/month with 1,200 minutes and business plans at $40/user/month offer unlimited transcription and additional features.</p>'
),

(
  'Mem AI',
  'mem-ai',
  'https://logo.clearbit.com/mem.ai',
  'https://mem.ai',
  'AI-powered note-taking app that automatically organizes your notes and lets you chat with your entire knowledge base.',
  'Mem is an AI-first note-taking and knowledge management application that uses AI to automatically organize your notes without manual tagging or folder structures. Its AI assistant (Mem Chat) can answer questions using your entire note library, surface relevant information, and help you write new content based on your existing knowledge.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  14.99,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"ai_organization": true, "knowledge_chat": true, "auto_tagging": true, "smart_search": true, "writing_assistant": true, "bi_directional_links": true}',
  ARRAY['AI automatically organizes notes', 'Chat with your entire knowledge base', 'No manual tagging required', 'Excellent search capabilities'],
  ARRAY['Smaller user base than Notion/Obsidian', 'Mobile app needs improvement', 'AI features can be slow'],
  7.5,
  980000,
  2020,
  'Mem AI is an AI-first note-taking app that auto-organizes your notes and lets you chat with your knowledge base for instant information retrieval.',
  '<h2>What is Mem AI?</h2><p>Mem is an AI-powered note-taking application that reimagines how we capture and organize knowledge. Unlike traditional note apps that require manual organization, Mem''s AI automatically structures your notes and makes everything instantly findable.</p><h2>Key Features</h2><p>Mem''s standout feature is its AI organization — it automatically tags, links, and surfaces relevant notes without any manual effort. Mem Chat allows you to have a conversation with your entire note library, asking questions and getting answers based on your personal knowledge base.</p><h2>Pricing</h2><p>Mem offers a free tier with basic features. Mem Pro at $14.99/month unlocks unlimited AI features, advanced search, and the full Mem Chat experience with your complete knowledge base.</p>'
),

(
  'Reclaim AI',
  'reclaim-ai',
  'https://logo.clearbit.com/reclaim.ai',
  'https://reclaim.ai',
  'AI scheduling assistant that automatically protects time for tasks, habits, and meetings in Google Calendar.',
  'Reclaim AI is an intelligent scheduling tool that automatically optimizes your Google Calendar. It finds the best times for tasks, meetings, and personal habits, then automatically schedules and defends that time. Reclaim learns your preferences and energy levels to schedule deep work when you''re most productive.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  10.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"auto_scheduling": true, "habit_protection": true, "task_integration": true, "google_calendar": true, "smart_meetings": true, "focus_time": true}',
  ARRAY['Automatically defends focus time', 'Learns your scheduling preferences', 'Integrates with task managers', 'Reduces scheduling meetings'],
  ARRAY['Google Calendar only (no Outlook native)', 'Learning curve for initial setup', 'Less useful for simple schedules'],
  8.0,
  1200000,
  2020,
  'Reclaim AI automatically schedules tasks, habits, and focus time in your Google Calendar. Protect your most productive hours with AI scheduling.',
  '<h2>What is Reclaim AI?</h2><p>Reclaim AI is an intelligent calendar automation tool that takes the friction out of time management. It integrates with your Google Calendar to automatically find and protect time for deep work, habits, and tasks based on your priorities and preferences.</p><h2>Key Features</h2><p>Reclaim automatically schedules tasks from your connected task managers (Todoist, Asana, Linear, etc.), protects recurring habits like exercise and lunch, and optimizes meeting times based on everyone''s availability and preferences. It defends your high-energy hours for focused deep work.</p><h2>Pricing</h2><p>Reclaim offers a free plan with basic scheduling features. Starter plans at $10/user/month unlock advanced task automation, and Business plans at $15/user/month add team features and analytics.</p>'
),

(
  'Clockwise',
  'clockwise',
  'https://logo.clearbit.com/getclockwise.com',
  'https://www.getclockwise.com',
  'AI calendar assistant that intelligently optimizes team schedules to maximize focus time and reduce scheduling conflicts.',
  'Clockwise is an AI-powered time management platform that optimizes calendars for both individuals and teams. Its AI understands meeting patterns, preferences, and priorities to automatically create focus time blocks, move flexible meetings to better slots, and reduce fragmented schedules across your entire organization.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  6.75,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"focus_time_creation": true, "meeting_optimization": true, "team_scheduling": true, "slack_integration": true, "google_calendar": true, "calendar_analytics": true}',
  ARRAY['Excellent team scheduling optimization', 'Creates protected focus time blocks', 'Reduces back-and-forth scheduling', 'Calendar analytics insights'],
  ARRAY['Best features require team adoption', 'Limited Outlook support', 'Some users report over-moving meetings'],
  7.8,
  950000,
  2016,
  'Clockwise is an AI calendar assistant that maximizes team focus time by intelligently optimizing schedules and automating meeting coordination.',
  '<h2>What is Clockwise?</h2><p>Clockwise is an AI-powered calendar optimization platform designed to help individuals and teams get more done by protecting focused work time. Its intelligent scheduling engine understands your work patterns and preferences to build an ideal schedule automatically.</p><h2>Key Features</h2><p>Clockwise automatically creates Focus Time blocks in your calendar, intelligently moves flexible meetings to times that minimize schedule fragmentation, and coordinates team availability to find meeting times that work for everyone. It integrates with Slack to set your status based on your calendar.</p><h2>Pricing</h2><p>Clockwise offers a free plan for individuals. Teams plans start at $6.75/user/month with advanced optimization features, and Business plans at $11.50/user/month add enterprise controls and analytics.</p>'
),

(
  'Motion AI',
  'motion-ai',
  'https://logo.clearbit.com/usemotion.com',
  'https://www.usemotion.com',
  'AI-powered project and task manager that automatically builds your daily schedule based on tasks, deadlines, and meetings.',
  'Motion is an AI-powered productivity platform that combines task management, project planning, and calendar scheduling into one intelligent system. Its AI automatically creates and adjusts your daily schedule based on your tasks, deadlines, and meetings, rescheduling automatically when priorities change.',
  'c1000000-0000-0000-0000-000000000008',
  'paid',
  34.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"ai_scheduling": true, "task_management": true, "project_planning": true, "auto_rescheduling": true, "calendar_integration": true, "team_coordination": true}',
  ARRAY['Fully automated daily schedule building', 'Adapts automatically to changes', 'Combines tasks, projects, and calendar', 'Reduces planning overhead significantly'],
  ARRAY['Higher price point than alternatives', 'Learning curve for initial setup', 'Can feel rigid with heavy automation'],
  8.1,
  2100000,
  2019,
  'Motion AI automatically builds your daily schedule from tasks and deadlines. The AI project manager that reschedules itself when priorities change.',
  '<h2>What is Motion AI?</h2><p>Motion is an AI-powered productivity platform that automatically plans your day. By combining task management, project planning, and calendar scheduling in one place, Motion''s AI engine creates an optimized daily schedule and continuously adjusts it as priorities and circumstances change.</p><h2>Key Features</h2><p>Motion''s AI automatically schedules every task in your list based on priority, deadline, and available time slots. When your calendar changes or new urgent tasks arrive, it automatically reschedules everything to keep you on track. Team features allow coordinated project planning across your organization.</p><h2>Pricing</h2><p>Motion offers a 7-day free trial. Individual plans start at $34/month (or $19/month billed annually). Team plans are available at $20/user/month billed annually with project management features.</p>'
),

(
  'Fireflies.ai',
  'fireflies-ai',
  'https://logo.clearbit.com/fireflies.ai',
  'https://fireflies.ai',
  'AI meeting assistant that automatically records, transcribes, summarizes, and analyzes your team meetings across all platforms.',
  'Fireflies.ai is a comprehensive AI meeting assistant that automatically joins and records your video meetings, then provides accurate transcriptions, AI-generated summaries, and conversation analytics. It integrates with over 200 apps and allows teams to search across all past meetings with keyword and topic filters.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  18.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"auto_recording": true, "transcription": true, "ai_summaries": true, "conversation_intelligence": true, "200_plus_integrations": true, "searchable_meetings": true}',
  ARRAY['Supports all major video platforms', '200+ app integrations', 'Conversation intelligence analytics', 'Excellent search across meetings'],
  ARRAY['Free tier has limited storage', 'Transcription accuracy varies with accents', 'Bot joining can feel impersonal to guests'],
  8.2,
  5600000,
  2019,
  'Fireflies.ai automatically records, transcribes, and summarizes all your meetings. Search and analyze conversations across 200+ integrations.',
  '<h2>What is Fireflies.ai?</h2><p>Fireflies.ai is an AI-powered meeting assistant that takes care of all your meeting documentation automatically. Its AI bot joins your video calls, records everything, and delivers accurate transcriptions and comprehensive summaries within minutes of the meeting ending.</p><h2>Key Features</h2><p>Fireflies supports Zoom, Google Meet, Microsoft Teams, Webex, and phone calls. Beyond transcription, it provides conversation intelligence features like sentiment analysis, speaker analytics, and topic tracking. The powerful search allows you to find any moment across your entire meeting history.</p><h2>Pricing</h2><p>Fireflies offers a free plan with 800 minutes of storage per seat. Pro at $18/user/month provides unlimited storage and AI summaries. Business and Enterprise plans offer advanced analytics and custom integrations.</p>'
),

(
  'tl;dv',
  'tldv',
  'https://logo.clearbit.com/tldv.io',
  'https://tldv.io',
  'AI meeting recorder that creates timestamped highlights, AI summaries, and shareable clips from your video meetings.',
  'tl;dv (Too Long; Didn''t View) is an AI-powered meeting recorder focused on making meeting insights shareable and actionable. It records and transcribes meetings, then uses AI to generate summaries and identify key moments. Its highlight reel feature allows creating short video clips of important moments to share with stakeholders.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  29.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"meeting_recording": true, "ai_summaries": true, "video_highlights": true, "timestamp_notes": true, "crm_integration": true, "multi_language": true}',
  ARRAY['Excellent video highlight clipping', 'Free tier is genuinely useful', 'CRM integration for sales teams', 'Multi-language support'],
  ARRAY['Pro features are expensive', 'Less analytics than Fireflies', 'Video storage costs can add up'],
  7.9,
  2800000,
  2021,
  'tl;dv records and transcribes video meetings with AI summaries and shareable highlight clips. Perfect for sales teams and async collaboration.',
  '<h2>What is tl;dv?</h2><p>tl;dv (Too Long; Didn''t View) is an AI meeting recorder that makes it easy to capture, share, and act on meeting insights. It is particularly popular among sales and customer success teams for its ability to create shareable video highlights from important meeting moments.</p><h2>Key Features</h2><p>tl;dv automatically records and transcribes Zoom and Google Meet calls. AI generates summaries and identifies key topics. The highlight clipping feature lets you select specific moments to share as short video clips. CRM integrations with Salesforce and HubSpot help teams log call insights automatically.</p><h2>Pricing</h2><p>tl;dv offers a generous free plan with unlimited recordings. Pro plans at $29/user/month unlock AI features, CRM integration, and advanced analytics for sales and revenue teams.</p>'
),

(
  'Sembly AI',
  'sembly',
  'https://logo.clearbit.com/sembly.ai',
  'https://sembly.ai',
  'AI team assistant that attends meetings, takes notes, and provides intelligent meeting analytics and risk identification.',
  'Sembly AI is an intelligent meeting assistant that goes beyond simple transcription to provide deep meeting intelligence. It automatically identifies risks, decisions, and commitments made in meetings, tracks follow-up items, and provides analytics on meeting effectiveness. Sembly supports over 35 languages and integrates with major video platforms.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  15.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"meeting_intelligence": true, "risk_identification": true, "decision_tracking": true, "35_languages": true, "smart_summaries": true, "team_analytics": true}',
  ARRAY['Advanced meeting intelligence beyond transcription', 'Risk and decision identification', '35+ language support', 'Team-wide meeting analytics'],
  ARRAY['Less well-known than Otter or Fireflies', 'Advanced features require higher tiers', 'Integration library smaller than competitors'],
  7.6,
  680000,
  2020,
  'Sembly AI attends your meetings to capture notes, identify risks and decisions, and provide team-wide meeting intelligence in 35+ languages.',
  '<h2>What is Sembly AI?</h2><p>Sembly AI is an intelligent meeting assistant that attends your online meetings to capture comprehensive notes and provide advanced meeting intelligence. It goes beyond simple transcription to identify business risks, track decisions, and monitor commitments made during meetings.</p><h2>Key Features</h2><p>Sembly supports over 35 languages and integrates with Zoom, Google Meet, and Microsoft Teams. Its AI identifies key items like risks, decisions, issues, and action items automatically. Team dashboards provide analytics on meeting patterns and help track follow-through on commitments.</p><h2>Pricing</h2><p>Sembly offers a free personal plan with basic features. Professional plans at $15/user/month include advanced AI features and team analytics. Enterprise plans offer custom integrations and dedicated support.</p>'
),

(
  'Krisp',
  'krisp',
  'https://logo.clearbit.com/krisp.ai',
  'https://krisp.ai',
  'AI-powered noise cancellation and meeting assistant that removes background noise and provides real-time meeting transcription.',
  'Krisp is an AI communications app that removes background noise, voices, and echo from calls using on-device AI processing. It works with any communication app and requires no hardware changes. Krisp also offers AI meeting notes, transcription, and summary features to help teams capture and act on meeting insights.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  16.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"noise_cancellation": true, "background_voice_removal": true, "on_device_processing": true, "meeting_transcription": true, "ai_summaries": true, "works_with_any_app": true}',
  ARRAY['Best-in-class noise cancellation', 'Privacy-first on-device processing', 'Works with any communication app', 'No hardware required'],
  ARRAY['Free tier has 60 min/week noise cancellation', 'AI notes are secondary to noise cancellation', 'Higher tiers needed for full features'],
  8.4,
  4200000,
  2018,
  'Krisp uses AI to cancel background noise on any call, plus offers meeting transcription and summaries. The best noise cancellation tool for remote workers.',
  '<h2>What is Krisp?</h2><p>Krisp is an AI-powered communications tool best known for its industry-leading background noise cancellation. It uses on-device AI to remove background noise, echo, and unwanted voices from your calls in real time, working with any communication application without requiring special hardware.</p><h2>Key Features</h2><p>Krisp processes audio entirely on your device for maximum privacy. Beyond noise cancellation, it offers AI meeting notes, transcription, and call summaries. It integrates as a virtual microphone and speaker with Zoom, Teams, Slack, and any other communication app.</p><h2>Pricing</h2><p>Krisp offers a free tier with 60 minutes per week of noise cancellation. Pro plans at $16/month provide unlimited noise cancellation, AI meeting notes, and additional communication features.</p>'
),

(
  'Fellow App',
  'fellow-app',
  'https://logo.clearbit.com/fellow.app',
  'https://fellow.app',
  'AI meeting management platform for collaborative agendas, real-time notes, action items, and team accountability.',
  'Fellow is an AI-powered meeting management platform designed to make every meeting productive and accountable. It provides collaborative meeting agendas, real-time note-taking with AI assistance, automatic action item tracking, and meeting feedback. Fellow integrates with calendars, task managers, and video platforms to streamline the entire meeting lifecycle.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  9.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"collaborative_agendas": true, "ai_meeting_notes": true, "action_item_tracking": true, "meeting_feedback": true, "one_on_one_tools": true, "performance_reviews": true}',
  ARRAY['Excellent for structured meetings and 1-on-1s', 'Collaborative agenda building', 'Strong accountability features', 'Good manager/team workflows'],
  ARRAY['Better for structured meetings than casual calls', 'Requires team adoption for best results', 'Some features overlap with project managers'],
  7.9,
  1400000,
  2017,
  'Fellow App is an AI meeting management tool for collaborative agendas, AI notes, and action item tracking. Built for accountable, productive meetings.',
  '<h2>What is Fellow App?</h2><p>Fellow is an AI-powered meeting management platform that helps teams run more productive and accountable meetings. It covers the entire meeting lifecycle from agenda creation to follow-up, helping managers and teams build better meeting habits.</p><h2>Key Features</h2><p>Fellow enables collaborative meeting agenda building before meetings begin, AI-assisted note-taking during meetings, and automatic action item tracking afterward. Dedicated one-on-one meeting templates help managers and their direct reports maintain productive regular check-ins. Meeting feedback features help teams continuously improve.</p><h2>Pricing</h2><p>Fellow offers a free plan for small teams with basic features. Pro plans at $9/user/month add AI meeting transcription, unlimited meeting history, and integrations. Business plans at $25/user/month include advanced analytics.</p>'
),

(
  'Read AI',
  'read-ai',
  'https://logo.clearbit.com/read.ai',
  'https://www.read.ai',
  'AI meeting copilot that provides real-time transcription, sentiment analysis, engagement metrics, and comprehensive meeting reports.',
  'Read AI is a comprehensive AI meeting intelligence platform that transcribes meetings in real time while simultaneously analyzing engagement, sentiment, and meeting effectiveness. It provides detailed meeting reports with speaker analytics, key topics, and action items. Read AI also offers an AI-powered email and messaging assistant.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  19.75,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"real_time_transcription": true, "sentiment_analysis": true, "engagement_metrics": true, "meeting_reports": true, "email_assistant": true, "speaker_analytics": true}',
  ARRAY['Rich meeting intelligence and analytics', 'Engagement and sentiment tracking', 'Comprehensive meeting reports', 'Email assistant included'],
  ARRAY['Can feel overly analytical for casual teams', 'Privacy concerns with sentiment tracking', 'Higher tier needed for best features'],
  7.8,
  1100000,
  2021,
  'Read AI provides real-time meeting transcription with sentiment analysis, engagement metrics, and comprehensive meeting intelligence reports.',
  '<h2>What is Read AI?</h2><p>Read AI is an AI meeting intelligence platform that goes beyond transcription to provide deep insights into your meetings. It analyzes participant engagement, conversation sentiment, and meeting effectiveness in real time, helping teams continuously improve how they collaborate.</p><h2>Key Features</h2><p>Read AI automatically joins and transcribes meetings, while simultaneously tracking engagement levels, sentiment, and key topics. Post-meeting reports include action items, key decisions, and speaker analytics. The platform also includes an AI email assistant that helps you draft and manage email communication.</p><h2>Pricing</h2><p>Read AI offers a free tier with 5 meeting transcriptions per month. Pro plans at $19.75/user/month provide unlimited transcriptions, full AI reports, and advanced analytics features.</p>'
),

(
  'Airgram',
  'airgram',
  'https://logo.clearbit.com/airgram.io',
  'https://www.airgram.io',
  'AI-powered meeting assistant with collaborative notes, agenda templates, and automatic transcription for video meetings.',
  'Airgram is an AI meeting assistant that combines collaborative meeting notes, agenda templates, and automatic video transcription. It allows teams to take structured meeting notes in real time, automatically transcribes and records meetings, and generates AI summaries. Airgram offers a library of meeting templates for recurring meeting types.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  18.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"collaborative_notes": true, "agenda_templates": true, "auto_transcription": true, "ai_summaries": true, "video_recording": true, "zoom_integration": true}',
  ARRAY['Good template library for meeting types', 'Collaborative real-time note-taking', 'Clean and intuitive interface', 'Solid free tier'],
  ARRAY['Smaller integration library than competitors', 'Less advanced AI than Fireflies', 'Limited to video call platforms'],
  7.4,
  580000,
  2021,
  'Airgram is an AI meeting assistant with collaborative notes, agenda templates, and automatic transcription for Zoom and Google Meet.',
  '<h2>What is Airgram?</h2><p>Airgram is an AI-powered meeting productivity tool that helps teams prepare for, run, and follow up on meetings more effectively. It combines collaborative agenda creation, real-time note-taking, and automatic AI transcription in a clean, user-friendly interface.</p><h2>Key Features</h2><p>Airgram provides a library of meeting templates for different types of meetings (standups, 1-on-1s, retrospectives, etc.), enabling structured and consistent meetings. It automatically records and transcribes Zoom and Google Meet calls, then generates AI summaries with action items and key takeaways.</p><h2>Pricing</h2><p>Airgram offers a free plan with 5 hours of transcription per month. Pro plans at $18/user/month provide unlimited transcription, advanced AI features, and additional collaboration tools.</p>'
),

(
  'Granola AI',
  'granola-ai',
  'https://logo.clearbit.com/granola.ai',
  'https://www.granola.ai',
  'AI notepad for meetings that turns your rough notes into polished, structured meeting notes using AI assistance.',
  'Granola is an AI-powered meeting notepad that enhances your manual note-taking with AI. Unlike bots that join your meetings, Granola runs locally on your Mac and listens to your meeting audio to help you take better notes. After the meeting, it combines your notes with the transcript to produce clean, structured meeting summaries.',
  'c1000000-0000-0000-0000-000000000008',
  'freemium',
  18.00,
  TRUE,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"local_processing": true, "enhances_manual_notes": true, "no_bot_required": true, "structured_summaries": true, "mac_native": true, "custom_templates": true}',
  ARRAY['No meeting bot - invisible to other participants', 'Enhances your own note-taking style', 'Privacy-friendly local processing', 'Clean polished output'],
  ARRAY['Mac only (no Windows support)', 'Requires you to take some notes yourself', 'Newer product with smaller user base'],
  8.0,
  420000,
  2023,
  'Granola AI is a Mac meeting notepad that enhances your notes with AI. No meeting bot required — works locally to create polished meeting summaries.',
  '<h2>What is Granola AI?</h2><p>Granola is a unique AI meeting assistant that takes a different approach to meeting notes. Instead of deploying a bot that visibly joins your meetings, Granola runs natively on your Mac and quietly listens to enhance your own note-taking with AI after the meeting.</p><h2>Key Features</h2><p>During a meeting, you take rough notes in Granola''s simple notepad interface. After the meeting, Granola''s AI combines your notes with the captured audio transcript to produce clean, well-structured meeting summaries. Custom templates let you define the format that works best for different meeting types.</p><h2>Pricing</h2><p>Granola offers 25 free meeting transcriptions to start. Pro plans at $18/month (or $14/month annually) provide unlimited meetings and access to advanced AI features and templates.</p>'
)

ON CONFLICT (slug) DO NOTHING;
