-- ============================================================
-- AIToolRadar Phase 6: 도구 200개 달성을 위한 확장 데이터 (Part 4)
-- 15 Tools (Guaranteed Unique to hit 200+)
-- ============================================================

INSERT INTO ai_tools (name, slug, logo_url, website_url, short_description, long_description, category_id, pricing_model, starting_price, has_free_trial, affiliate_url, affiliate_program, commission_type, commission_rate, features, pros, cons, rating, monthly_visits, founded_year, meta_description, content_html) VALUES

-- AI Video (3개)
('Hailuo AI', 'hailuo-ai', 'https://logo.clearbit.com/hailuo.ai', 'https://hailuo.ai', 'Minimax''s highly coherent text-to-video generator with excellent character consistency.', 'Hailuo AI (by Minimax) is an advanced video generation model that has recently gained massive popularity for its ability to maintain incredible character consistency and follow prompt instructions better than many Western alternatives.', 'c1000000-0000-0000-0000-000000000004', 'freemium', 0.00, true, NULL, NULL, NULL, NULL, '{"high_consistency": true, "anime_style_support": true, "prompt_adherence": true}', ARRAY['Outstanding character consistency', 'Generous free daily credits', 'Excels at dynamic motion'], ARRAY['Chinese phone number required for some features', 'Interface is basic'], 8.9, 2100000, 2024, 'Hailuo AI by Minimax is a breakthrough text-to-video model offering unparalleled character consistency and dynamic motion generation.', '<h2>What is Hailuo AI?</h2><p>Developed by Chinese AI startup Minimax, Hailuo AI burst onto the scene as a major competitor to Sora and Kling. It is uniquely capable of generating complex human emotions, interactions, and maintaining the exact same character appearance across wild camera movements.</p>'),

('LTX Studio', 'ltx-studio', 'https://logo.clearbit.com/lightricks.com', 'https://ltx.studio', 'AI filmmaking platform redefining the pre-production and storyboarding process.', 'LTX Studio by Lightricks goes beyond standard video generation. It is a full AI filmmaking environment where you can direct scenes, swap characters, change camera angles, and maintain perfect narrative consistency across an entire storyboard.', 'c1000000-0000-0000-0000-000000000004', 'freemium', 15.00, true, NULL, NULL, NULL, NULL, '{"storyboarding": true, "character_consistency": true, "camera_control": true, "scene_director": true}', ARRAY['Full control over camera angles', 'Maintains characters across scenes', 'Incredible pre-production tool'], ARRAY['Still in waitlist/beta phases', 'High learning curve for casual users', 'Final renders can sometimes be low resolution'], 9.1, 850000, 2024, 'LTX Studio is an AI filmmaking platform designed for directors and creators to storyboard, direct, and render consistent video scenes.', '<h2>What is LTX Studio?</h2><p>LTX Studio is not just a prompt-to-video generator; it''s a comprehensive director''s suite. You start with a script, and the AI generates a multi-scene storyboard. You can then individually tweak lighting, swap out actors, or move the camera in 3D space for every single shot before rendering the final film.</p>'),

('Vidu AI', 'vidu-ai', 'https://logo.clearbit.com/vidu.studio', 'https://vidu.studio', 'Fast and highly stylized AI video generator with deep 3D understanding.', 'Vidu AI is a robust video generation model capable of creating 1080p video clips with stunning cinematic lighting and localized physics simulation, competing directly with Luma and Runway.', 'c1000000-0000-0000-0000-000000000004', 'freemium', 9.99, true, NULL, NULL, NULL, NULL, '{"1080p_generation": true, "cinematic_lighting": true, "image_to_video": true}', ARRAY['Very fast generation times', 'Beautiful cinematic aesthetics', 'Strong prompt adherence'], ARRAY['Struggles with text rendering in video', 'Shorter maximum duration per clip'], 8.4, 1200000, 2024, 'Vidu AI generates highly stylized, cinematic 1080p videos from text and images with robust physics and lighting control.', '<h2>What is Vidu AI?</h2><p>Vidu AI stands out for its stylistic rendering and cinematic lighting. When fed an image, it excels at adding realistic environmental effects like smoke, rain, or moving light sources, making it a favorite for music video creators and VJs.</p>'),

-- AI Research / Productivity (3개)
('Elicit', 'elicit', 'https://logo.clearbit.com/elicit.com', 'https://elicit.com', 'AI research assistant that finds, extracts, and summarizes academic papers.', 'Elicit uses language models to help automate research workflows. It searches through 125 million+ academic papers, extracts key data points, and synthesizes findings into a neat, cited literature review matrix.', 'c1000000-0000-0000-0000-000000000008', 'freemium', 12.00, true, NULL, NULL, NULL, NULL, '{"literature_review": true, "data_extraction": true, "pdf_chat": true}', ARRAY['Invaluable for students and researchers', 'Prevents AI hallucinations by citing real papers', 'Extracts specific methodologies and sample sizes'], ARRAY['Focused strictly on academia, not general web search', 'Paid tier is practically required for heavy use'], 9.3, 3500000, 2021, 'Elicit is the leading AI research assistant. Automate literature reviews, find academic papers without perfect keywords, and extract data instantly.', '<h2>What is Elicit?</h2><p>Elicit is a godsend for anyone doing serious academic or market research. Instead of returning links like Google Scholar, Elicit reads the papers for you and pulls out exactly what you ask for—like the sample size, intervention, and specific outcomes—arranging them into a downloadable spreadsheet.</p>'),

('Consensus', 'consensus', 'https://logo.clearbit.com/consensus.app', 'https://consensus.app', 'AI search engine built specifically for finding evidence-based answers in scientific research.', 'Consensus takes your everyday questions and searches peer-reviewed scientific literature to find the answer. It provides a "Consensus Meter" showing what percentage of papers agree or disagree with a specific hypothesis.', 'c1000000-0000-0000-0000-000000000008', 'freemium', 8.99, true, NULL, NULL, NULL, NULL, '{"consensus_meter": true, "copilot_synthesis": true, "peer_reviewed_only": true}', ARRAY['Stops misinformation by relying only on science', 'Consensus Meter feature is incredibly useful', 'Very easy, Google-like interface'], ARRAY['Cannot answer non-scientific or pop-culture questions', 'Subscription needed for Copilot features'], 9.0, 4200000, 2022, 'Consensus AI is a search engine that uses artificial intelligence to find answers directly from peer-reviewed scientific studies.', '<h2>What is Consensus?</h2><p>If you''ve ever wondered "does coffee actually stunt growth?" and wanted a real scientific answer instead of a blog post, Consensus is the tool. It reads thousands of research abstracts and provides a synthesized answer, showing you exactly how much of the scientific community agrees.</p>'),

('SciSpace', 'scispace', 'https://logo.clearbit.com/typeset.io', 'https://typeset.io', 'AI copilot for reading and understanding complex research papers.', 'SciSpace (formerly Typeset) offers an interactive AI copilot that lives alongside PDF documents. It can explain confusing math equations, summarize dense paragraphs, and help format bibliographies instantly.', 'c1000000-0000-0000-0000-000000000008', 'freemium', 12.00, true, NULL, NULL, NULL, NULL, '{"pdf_explainer": true, "equation_solver": true, "literature_search": true, "citation_generator": true}', ARRAY['Explains complex math and charts easily', 'Chrome extension works on publisher websites', 'Multiple languages supported'], ARRAY['Interface can feel cluttered', 'Data extraction occasionally misses tables'], 8.7, 5500000, 2018, 'SciSpace is an AI copilot that helps you read, understand, and format academic research papers effortlessly.', '<h2>What is SciSpace?</h2><p>SciSpace acts as a tutor sitting next to you while you read dense material. Highlight a confusing paragraph or a complex algebraic equation, and the AI copilot will break it down into simple terms. It can also instantly format your paper into thousands of specific journal guidelines.</p>'),

-- AI Image / Design (3개)
('Recraft', 'recraft', 'https://logo.clearbit.com/recraft.ai', 'https://recraft.ai', 'Infinite AI design board specialized in vector art, icons, and 3D illustrations.', 'Recraft is a unique AI image generator built specifically for designers. Unlike tools that only output flattened PNGs, Recraft excels at generating true infinitely scalable SVG vector graphics, 3D icons, and complete brand asset sets.', 'c1000000-0000-0000-0000-000000000002', 'freemium', 20.00, true, NULL, NULL, NULL, NULL, '{"vector_generation": true, "svg_export": true, "brand_style_control": true, "icon_sets": true}', ARRAY['The only viable AI tool for true vector/SVG output', 'Incredible for UI/UX designers needing icons', 'Maintains strict brand color palettes'], ARRAY['Not meant for photorealism', 'Interface tailored for pros, less intuitive for beginners'], 9.2, 2800000, 2023, 'Recraft is the best AI generator for vector art and icons. Generate infinitely scalable SVGs and control exact brand color palettes.', '<h2>What is Recraft?</h2><p>Recraft solves the biggest problem designers have with Midjourney: scalability. Because Recraft can output true SVG vectors, the illustrations and icons it generates can be blown up to the size of a billboard without losing quality. It is an absolute must-have for web designers and marketing teams.</p>'),

('Freepik Pikaso', 'freepik-pikaso', 'https://logo.clearbit.com/freepik.com', 'https://freepik.com', 'Real-time AI drawing canvas where your rough sketches turn into high-quality art instantly.', 'Pikaso is Freepik''s real-time AI generation tool. Draw simple shapes on one side of the screen, and watch the AI render a highly detailed, photorealistic, or stylized image on the other side in real-time.', 'c1000000-0000-0000-0000-000000000002', 'freemium', 15.00, true, NULL, NULL, NULL, NULL, '{"realtime_sketch_to_image": true, "webcam_support": true, "upscaling": true}', ARRAY['Zero latency real-time generation', 'Extremely fun and intuitive to use', 'Backed by Freepik''s massive asset library'], ARRAY['Requires premium for high-res downloads', 'Specific compositional control can be finicky'], 8.8, 12000000, 2023, 'Freepik Pikaso brings real-time AI drawing to life. Sketch roughly and let the AI instantly render stunning, photorealistic scenes.', '<h2>What is Freepik Pikaso?</h2><p>Pikaso lowers the barrier to entry for AI art. Instead of struggling with complex text prompts ("a cat sitting on a chair, 8k, unreal engine"), you simply draw a stick figure and a square, type "cat on a chair," and the AI fills in the details instantly as your brush moves.</p>'),

('Krea AI', 'krea-ai', 'https://logo.clearbit.com/krea.ai', 'https://krea.ai', 'Next-generation AI creative suite featuring real-time image generation and stunning AI upscaling.', 'Krea AI is a comprehensive suite that became famous for its hyper-fast real-time image generation and incredibly hallucinated AI upscaling, able to add pores, textures, and microscopic details to blurry images.', 'c1000000-0000-0000-0000-000000000002', 'freemium', 30.00, true, NULL, NULL, NULL, NULL, '{"realtime_generation": true, "ai_upscaling_enhancement": true, "screen_capture_mode": true}', ARRAY['Upscaler rivals Magnific AI but is cheaper', 'Screen capture mode works with desktop 3D software', 'Beautiful, sleek UI'], ARRAY['High cost for the pro tier', 'Real-time generation requires strong internet connection'], 9.3, 4100000, 2023, 'Krea AI offers cutting-edge real-time AI image generation and phenomenal AI upscaling that adds stunning details to low-resolution photos.', '<h2>What is Krea AI?</h2><p>Krea operates at the bleeding edge of generative AI. It offers two main features: a real-time canvas where it generates images as fast as you can draw or move shapes, and an Enhance feature that acts as a magical upscaler, interpreting blurry pixels and replacing them with high-fidelity textures.</p>'),

-- AI Audio / Voice (2개)
('Kits AI', 'kits-ai', 'https://logo.clearbit.com/kits.ai', 'https://kits.ai', 'AI voice cloning and vocal stem separation platform built specifically for music producers.', 'Kits AI is an AI vocal generation tool officially partnered with artists. It provides royalty-free AI artist voices, instrument generation, and top-tier vocal track separation for music producers.', 'c1000000-0000-0000-0000-000000000007', 'freemium', 9.99, true, NULL, NULL, NULL, NULL, '{"artist_voice_cloning": true, "royalty_free_voices": true, "stem_separation": true, "vst_plugin": true}', ARRAY['Fully cleared, royalty-free artist voices', 'Includes a native VST plugin for DAWs', 'Excellent stem separation quality'], ARRAY['Geared specifically towards musicians, not podcasters', 'Some premium voices require revenue splitting'], 8.5, 1800000, 2023, 'Kits AI is the premier AI voice toolkit for music producers, offering cleared, royalty-free artist voices and powerful stem separation.', '<h2>What is Kits AI?</h2><p>Unlike standard text-to-speech tools, Kits AI is built for music. It allows producers to record a vocal melody themselves, and then transform that audio into the voice of a different singer or even an instrument. Crucially, they partner directly with artists, ensuring all voices are legal and royalty-free to use in commercial tracks.</p>'),

('Cassette AI', 'cassette-ai', 'https://logo.clearbit.com/cassette.ai', 'https://cassette.ai', 'AI music copilot that helps you build beats and tracks from text prompts.', 'Cassette AI uses latent diffusion to generate music. Designed to be a collaborative copilot, it allows users to specify length, genre, BPM, and mood to generate high-quality backing tracks, beats, and loops.', 'c1000000-0000-0000-0000-000000000007', 'freemium', 4.99, true, NULL, NULL, NULL, NULL, '{"text_to_beat": true, "custom_bpm": true, "loop_generation": true}', ARRAY['Great for generating lo-fi chillhop beats', 'Affordable pro plans', 'Easy to export loops for video editing'], ARRAY['Audio fidelity varies by genre', 'Less capable than Suno for full songs with vocals'], 7.8, 450000, 2023, 'Cassette AI generates royalty-free beats, loops, and backing tracks from text prompts. The perfect AI copilot for beatmakers and video editors.', '<h2>What is Cassette AI?</h2><p>Cassette AI focuses entirely on instrumental music generation. If you are a YouTube creator looking for background music, or a producer looking for a starting loop to build a hip-hop beat around, Cassette provides high-quality, royalty-free audio tracks customized exactly to your prompt.</p>'),

-- AI SEO / Blogging (4개)
('Byword', 'byword-ai', 'https://logo.clearbit.com/byword.ai', 'https://byword.ai', 'Programmatic AI SEO content generator that creates hundreds of articles at scale.', 'Byword AI is designed for programmatic SEO. You can feed it a list of 1,000 keywords, and it will generate high-quality, formatted, and interlinked articles for every single one, pushing them directly to your CMS.', 'c1000000-0000-0000-0000-000000000010', 'paid', 99.00, false, NULL, NULL, NULL, NULL, '{"bulk_generation": true, "cms_integration": true, "custom_image_generation": true}', ARRAY['Unmatched capacity for scale', 'Bypasses AI detectors well', 'Seamless WordPress/Webflow integration'], ARRAY['Very high starting price', 'No free trial without a sales call', 'Content can become repetitive at extreme scale'], 8.6, 600000, 2022, 'Byword AI generates high-quality SEO content at massive scale. Input thousands of keywords and auto-publish directly to your CMS.', '<h2>What is Byword?</h2><p>Byword isn''t meant for writing a single blog post; it''s meant for building massive content moats. Ideal for niche site builders and enterprise SEOs, it takes a CSV of keywords and generates comprehensive, fully-formatted articles in bulk, bypassing the traditional single-prompt workflow entirely.</p>'),

('KoalaWriter', 'koala-writer', 'https://logo.clearbit.com/koala.sh', 'https://koala.sh', 'One-click AI article writer powered by live Amazon data and real-time search.', 'KoalaWriter (by Koala.sh) is a favorite among affiliate marketers. It can scrape the live internet and Amazon product pages, allowing it to write highly accurate, up-to-date affiliate roundups (e.g., "Best Laptops 2026") with actual product specs and pros/cons.', 'c1000000-0000-0000-0000-000000000010', 'paid', 9.00, true, NULL, NULL, NULL, NULL, '{"amazon_integration": true, "live_search": true, "affiliate_roundups": true, "one_click_publish": true}', ARRAY['The absolute best AI for Amazon affiliates', 'Produces incredibly structured, human-like formatting', 'Uses live data to prevent hallucinations'], ARRAY['Credit system can be confusing', 'Premium models burn through words quickly'], 9.3, 1100000, 2023, 'KoalaWriter pulls live Amazon data to write perfect affiliate product roundups and reviews. The ultimate tool for niche site owners.', '<h2>What is KoalaWriter?</h2><p>KoalaWriter changed the game for affiliate marketing SEO. Instead of just making up content, it actively queries Google and Amazon in the background. If you ask it to review a specific camera, it retrieves the actual specs, current price, and user reviews, writing a factual article instantly in your WordPress backend.</p>'),

('Agility Writer', 'agility-writer', 'https://logo.clearbit.com/agilitywriter.ai', 'https://agilitywriter.ai', 'Advanced AI writing tool that produces 3,000+ word powerhouse articles designed to rank.', 'Agility Writer focuses on long-form, comprehensive content. It generates massive, deeply researched articles with custom structural outlines, factual data tables, and NLP optimization designed specifically to outrank competitors on Google.', 'c1000000-0000-0000-0000-000000000010', 'paid', 25.00, false, NULL, NULL, NULL, NULL, '{"long_form_content": true, "advanced_outlines": true, "data_tables": true, "nlp_optimization": true}', ARRAY['Generates massive, detailed articles (3000+ words)', 'Includes beautifully designed HTML tables', 'High factual accuracy'], ARRAY['Can take 5-10 minutes to generate an article', 'More complex to configure than one-click writers'], 8.9, 750000, 2023, 'Agility Writer creates massive, SEO-optimized powerhouse articles with advanced outlines and factual data tables designed to rank #1 on Google.', '<h2>What is Agility Writer?</h2><p>While many tools output short 800-word fluff pieces, Agility Writer specializes in deep, authoritative content. It scrapes the top-ranking articles for your keyword, extracts the core entities, and generates a massive pillar post complete with FAQ schema, tables, and internal links.</p>'),

('ZimmWriter', 'zimmwriter', 'https://logo.clearbit.com/zimmwriter.com', 'https://www.zimmwriter.com', 'Local desktop AI writing software for Windows that offers unlimited generation via your own API keys.', 'ZimmWriter is unique because it is a downloadable Windows application rather than a cloud SaaS. You plug in your own OpenAI/Anthropic API keys, allowing you to generate massive amounts of SEO content at wholesale API costs rather than paying expensive monthly subscriptions.', 'c1000000-0000-0000-0000-000000000001', 'paid', 14.97, false, NULL, NULL, NULL, NULL, '{"windows_desktop_app": true, "bring_your_own_key": true, "local_generation": true, "magic_command": true}', ARRAY['Saves thousands of dollars via BYOK pricing', 'Works universally across any Windows text field', 'Incredibly deep SEO features'], ARRAY['Windows only (no Mac support)', 'UI is very old-school and utilitarian', 'Steep learning curve'], 8.8, 300000, 2022, 'ZimmWriter is a Windows desktop AI writer. Use your own API keys to generate unlimited, highly-optimized SEO blog posts at wholesale cost.', '<h2>What is ZimmWriter?</h2><p>ZimmWriter is an underground favorite in the SEO community because of its Bring Your Own Key (BYOK) model. Instead of paying $100/month for a SaaS wrapper, you buy the software, use your own OpenAI API key, and write tens of thousands of words for pennies. It also functions globally, meaning you can highlight text anywhere in Windows, press a shortcut, and the AI will rewrite it instantly.</p>')

ON CONFLICT (slug) DO NOTHING;
