-- ============================================================
-- AIToolRadar Phase 6: 도구 200개 달성을 위한 확장 데이터 (Part 1/3)
-- 10 Tools (Productivity, Audio & Music)
-- ============================================================

INSERT INTO ai_tools (name, slug, logo_url, website_url, short_description, long_description, category_id, pricing_model, starting_price, has_free_trial, affiliate_url, affiliate_program, commission_type, commission_rate, features, pros, cons, rating, monthly_visits, founded_year, meta_description, content_html) VALUES

-- AI Productivity (5개)
('Mem AI', 'mem-ai', 'https://logo.clearbit.com/mem.ai', 'https://mem.ai', 'AI-powered workspace that organizes your notes and tasks automatically.', 'Mem AI is a self-organizing workspace that uses AI to connect your notes, tasks, and calendar. It automatically categorizes information, making it instantly retrievable without manual tagging or folder structuring.', 'c1000000-0000-0000-0000-000000000008', 'freemium', 14.99, true, NULL, NULL, NULL, NULL, '{"self_organizing": true, "ai_search": true, "task_management": true, "calendar_sync": true}', ARRAY['No manual organization needed', 'Extremely fast search', 'Clean user interface'], ARRAY['Expensive for individuals', 'Learning curve for the new paradigm', 'Mobile app needs improvement'], 8.2, 850000, 2019, 'Mem AI is an AI-powered workspace that organizes your notes automatically. Say goodbye to folders and tags.', '<h2>What is Mem AI?</h2><p>Mem is an AI-first note-taking and workspace app that completely eliminates the need for manual organization. By continuously analyzing your notes and workflows, it surfaces relevant information exactly when you need it.</p>'),

('Taskade', 'taskade', 'https://logo.clearbit.com/taskade.com', 'https://taskade.com', 'AI productivity workspace for teams with built-in task management and mind mapping.', 'Taskade is a unified workspace where teams can manage tasks, write notes, and chat in real-time. Integrated AI agents help generate outlines, summarize meeting notes, and automate repetitive workflows.', 'c1000000-0000-0000-0000-000000000008', 'freemium', 4.00, true, NULL, NULL, NULL, NULL, '{"ai_agents": true, "mind_mapping": true, "video_chat": true, "task_management": true}', ARRAY['Very affordable pricing', 'Generous free tier', 'Multiple project views including mind maps'], ARRAY['UI can feel cluttered', 'AI output sometimes generic', 'Takes time to set up workflows'], 8.5, 1200000, 2017, 'Taskade is an AI workspace for teams combining tasks, notes, mind maps, and video chat into one platform.', '<h2>What is Taskade?</h2><p>Taskade replaces multiple productivity tools by combining task management, document collaboration, and team communication into a single unified workspace powered by AI agents.</p>'),

('Motion', 'motion-app', 'https://logo.clearbit.com/usemotion.com', 'https://usemotion.com', 'AI executive assistant that automatically schedules your tasks and meetings.', 'Motion uses artificial intelligence to automatically plan your day. It takes your tasks, meetings, and working hours, and builds the perfect schedule to maximize productivity and ensure deadlines are met.', 'c1000000-0000-0000-0000-000000000008', 'paid', 19.00, true, NULL, NULL, NULL, NULL, '{"auto_scheduling": true, "calendar_management": true, "task_prioritization": true, "meeting_scheduler": true}', ARRAY['Saves hours of manual planning', 'Automatically adjusts to delays', 'Great for managing multiple projects'], ARRAY['Very expensive', 'No free plan', 'Steep learning curve to trust the AI'], 8.1, 2100000, 2019, 'Motion is an AI calendar and task manager that automatically schedules your day to guarantee deadlines are met.', '<h2>What is Motion?</h2><p>Motion acts as your personal AI executive assistant. Instead of manually moving tasks around your calendar, Motion uses complex algorithms to prioritize your work, schedule tasks around meetings, and shift things automatically when priorities change.</p>'),

('Reclaim AI', 'reclaim-ai', 'https://logo.clearbit.com/reclaim.ai', 'https://reclaim.ai', 'Smart calendar assistant for Google Calendar that defends your time block automatically.', 'Reclaim is an AI scheduling app that integrates deeply with Google Calendar to automatically block time for your habits, tasks, and regular routines. It defends your deep work time while remaining flexible for urgent meetings.', 'c1000000-0000-0000-0000-000000000008', 'freemium', 8.00, true, NULL, NULL, NULL, NULL, '{"time_blocking": true, "habit_tracking": true, "google_calendar_sync": true, "task_integration": true}', ARRAY['Integrates with existing task managers', 'Flexible time blocking', 'Generous free tier', 'Great UI/UX'], ARRAY['Google Calendar only', 'Team features are pricey', 'Can over-schedule if not careful'], 8.6, 1800000, 2019, 'Reclaim AI automatically blocks time for tasks and habits in Google Calendar. Defend your deep work time effortlessly.', '<h2>What is Reclaim AI?</h2><p>Reclaim is the smartest way to manage your Google Calendar. It automatically finds time for your tasks, habits, one-on-ones, and breaks, shifting them fluidly as your schedule changes to ensure you always have time for what matters.</p>'),

('Notion AI', 'notion-ai', 'https://logo.clearbit.com/notion.so', 'https://notion.so/product/ai', 'Integrated AI assistant inside Notion for writing, summarizing, and data extraction.', 'Notion AI brings the power of artificial intelligence directly into your Notion workspace. It can generate text, summarize long documents, translate languages, and even extract structured data from messy notes.', 'c1000000-0000-0000-0000-000000000008', 'paid', 10.00, true, NULL, NULL, NULL, NULL, '{"text_generation": true, "summarization": true, "data_extraction": true, "translation": true}', ARRAY['Seamlessly integrated into Notion', 'Q&A feature searches entire workspace', 'Excellent text summarization'], ARRAY['Additional monthly cost on top of Notion', 'Context window can be limited', 'Requires existing Notion usage'], 8.9, 8500000, 2022, 'Notion AI elevates your workspace by automating writing, summarizing notes, and retrieving information instantly.', '<h2>What is Notion AI?</h2><p>Notion AI is deeply integrated into the Notion ecosystem. The AI can write, rewrite, summarize, translate, and brainstorm right alongside your documents, making it an indispensable tool for heavy Notion users.</p>'),

-- AI Audio & Music (5개)
('Adobe Podcast', 'adobe-podcast', 'https://logo.clearbit.com/adobe.com', 'https://podcast.adobe.com', 'AI-powered audio recording and ending tool that makes voice recordings sound like they were recorded in a studio.', 'Adobe Podcast offers AI-powered audio tools including its famous Enhance Speech feature, which removes background noise and echoes from voice recordings, making even phone recordings sound like they were recorded in a professional studio.', 'c1000000-0000-0000-0000-000000000007', 'freemium', 9.99, true, NULL, NULL, NULL, NULL, '{"enhance_speech": true, "mic_check": true, "browser_recording": true, "multi_track_editing": true}', ARRAY['Incredible speech enhancement quality', 'Free tier is very generous', 'Web-based interface'], ARRAY['Limited editing tools compared to Audition', 'Requires Adobe account', 'Processing can be slow for long files'], 9.1, 4500000, 2022, 'Adobe Podcast uses AI to make any voice recording sound professional. Remove background noise and echo for free.', '<h2>What is Adobe Podcast?</h2><p>Adobe Podcast is a web-based audio recording and editing platform. Its standout feature, Enhance Speech, uses advanced machine learning to clean up noisy dialogue, making it an essential tool for podcasters and video creators.</p>'),

('Cleanvoice', 'cleanvoice', 'https://logo.clearbit.com/cleanvoice.ai', 'https://cleanvoice.ai', 'AI that automatically edits your podcast episodes by removing filler words and mouth sounds.', 'Cleanvoice is an AI tool that removes filler words, stuttering, and mouth sounds from your audio or video recordings. It saves podcasters hours of tedious manual editing by delivering a cleaned-up track in minutes.', 'c1000000-0000-0000-0000-000000000007', 'paid', 10.00, true, NULL, NULL, NULL, NULL, '{"filler_word_removal": true, "mouth_sound_removal": true, "multilingual": true, "timeline_export": true}', ARRAY['Massive time saver for podcasters', 'Supports multiple languages', 'Exports directly to Premiere/Audition'], ARRAY['Credit-based pricing can add up', 'No integrated recording feature', 'Sometimes overly aggressive editing'], 8.3, 300000, 2021, 'Cleanvoice AI removes filler words and mouth sounds from podcasts automatically. Edit hours of audio in minutes.', '<h2>What is Cleanvoice?</h2><p>Cleanvoice is a specialized AI audio editor designed purely for spoken word content. It automatically detecting and stripping out umms, ahhs, stutters, and dead air, leaving you with a crisp, professional-sounding recording.</p>'),

('Riverside.fm', 'riverside-fm', 'https://logo.clearbit.com/riverside.fm', 'https://riverside.fm', 'High-quality remote podcast recording platform with AI transcription and editing.', 'Riverside is the leading remote recording platform used by top podcasters. It records uncompressed audio and 4K video locally, ensuring perfect quality regardless of internet connection. Its AI features include Magic Clips, automatic transcription, and speaker separation.', 'c1000000-0000-0000-0000-000000000007', 'freemium', 15.00, true, NULL, NULL, NULL, NULL, '{"local_recording": true, "4k_video": true, "magic_clips": true, "ai_transcription": true, "text_based_editing": true}', ARRAY['Studio quality remote recording', 'Magic Clips for social media', 'Excellent text-based editor', 'Reliable separated tracks'], ARRAY['Can be heavy on computer resources', 'Mobile app lacks advanced features', 'Higher tier needed for continuous support'], 8.8, 6200000, 2020, 'Riverside.fm is a remote podcast recording studio with AI transcription and social media clip generation.', '<h2>What is Riverside?</h2><p>Riverside makes it easy to record studio-quality podcasts and video interviews remotely. By recording locally on each participant''s device and using AI to generate transcripts and clips, it provides an end-to-end podcasting workflow.</p>'),

('Podcastle', 'podcastle', 'https://logo.clearbit.com/podcastle.ai', 'https://podcastle.ai', 'All-in-one web-based podcast creation platform with AI voice cloning and audio enhancing.', 'Podcastle is a comprehensive AI-powered audio creation platform that combines recording, editing, and publishing. It features tools like Magic Dust for audio enhancement, AI voice cloning, and text-to-speech for generating podcast episodes entirely from scripts.', 'c1000000-0000-0000-0000-000000000007', 'freemium', 11.99, true, NULL, NULL, NULL, NULL, '{"audio_recording": true, "magic_dust_enhancement": true, "voice_cloning": true, "remote_interviews": true}', ARRAY['All-in-one podcasting platform', 'Excellent Magic Dust feature', 'Voice cloning included in pro plans', 'Very intuitive interface'], ARRAY['Browser-based can be less stable', 'Transcription accuracy varies', 'Mobile app is somewhat basic'], 8.4, 2100000, 2021, 'Podcastle is an AI-powered audio creation suite. Record, edit, enhance recordings, and clone your voice in the browser.', '<h2>What is Podcastle?</h2><p>Podcastle brings professional audio production to the browser. With its AI-powered features, anyone can record remote interviews, enhance audio quality with a single click, or use text-to-speech to create realistic voiceovers.</p>'),

('Suno AI', 'suno-ai', 'https://logo.clearbit.com/suno.com', 'https://suno.com', 'Create original full-length songs with vocals and instrumentation from text prompts.', 'Suno is a breakthrough AI music generation platform that can instantly create realistic, full-produced songs complete with vocals, lyrics, and instrumentation in almost any genre from a simple text description.', 'c1000000-0000-0000-0000-000000000007', 'freemium', 8.00, true, NULL, NULL, NULL, NULL, '{"text_to_music": true, "vocal_generation": true, "custom_lyrics": true, "instrumental_mode": true}', ARRAY['Incredible vocal realism', 'Fast generation speed', 'Supports extremely specific genre prompts', 'Generous daily free credits'], ARRAY['Audio quality can sometimes sound compressed', 'Less control over individual stems', 'Copyright ambiguity on training data'], 9.2, 28000000, 2023, 'Suno AI generates full-length songs with vocals from text prompts. The best AI music creator for musicians and hobbyists.', '<h2>What is Suno?</h2><p>Suno AI is revolutionizing music creation by allowing anyone to generate high-quality, full-length songs just by describing them. Whether you want a heavy metal track about coding or a pop song about your dog, Suno generates original music and vocals in seconds.</p>')

ON CONFLICT (slug) DO NOTHING;
