-- ============================================================
-- AIToolRadar Phase 6: 도구 200개 달성을 위한 확장 데이터 (Part 3/3)
-- 8 Tools (Chatbots, Audio, Writing)
-- ============================================================

INSERT INTO ai_tools (name, slug, logo_url, website_url, short_description, long_description, category_id, pricing_model, starting_price, has_free_trial, affiliate_url, affiliate_program, commission_type, commission_rate, features, pros, cons, rating, monthly_visits, founded_year, meta_description, content_html) VALUES

-- AI Chatbots (3개)
('Claude', 'claude', 'https://logo.clearbit.com/anthropic.com', 'https://claude.ai', 'Anthropic''s safe, capable, and highly articulate AI assistant.', 'Claude is a next-generation AI assistant built by Anthropic. Known for its exceptional reasoning, large context window, and nuanced writing capabilities, Claude 3.5 Sonnet is widely considered one of the best models available for coding and complex analysis.', 'c1000000-0000-0000-0000-000000000006', 'freemium', 20.00, true, NULL, NULL, NULL, NULL, '{"large_context": true, "artifacts_ui": true, "vision_capabilities": true}', ARRAY['Exceptional writing style', 'Artifacts UI for interactive coding', 'Safe and reliable'], ARRAY['Stricter safety filters than competitors', 'Less internet searching capabilities'], 9.4, 55000000, 2021, 'Claude by Anthropic features a massive context window and the innovative Artifacts UI, making it a favorite for coding and writing.', '<h2>What is Claude?</h2><p>Claude is an AI assistant developed by Anthropic with a focus on safety and steerability. Its latest models offer a massive 200K token context window and introduce "Artifacts," a dedicated UI panel for interacting with generated code, documents, and SVGs.</p>'),

('Perplexity AI', 'perplexity-ai', 'https://logo.clearbit.com/perplexity.ai', 'https://perplexity.ai', 'AI conversational search engine that provides cited, accurate answers.', 'Perplexity AI functions as a "knowledge discovery engine." Instead of just generating text from its training data, it searches the live internet, reads multiple sources, and compiles a comprehensive answer complete with inline citations.', 'c1000000-0000-0000-0000-000000000006', 'freemium', 20.00, true, NULL, NULL, NULL, NULL, '{"live_web_search": true, "inline_citations": true, "copilot_mode": true}', ARRAY['Highly accurate and fact-checked', 'Provides source links for everything', 'Replaces traditional search engines'], ARRAY['Not ideal for creative writing', 'Can be slower than standard chatbots'], 9.1, 85000000, 2022, 'Perplexity AI is a conversational search engine that browses the live web to provide accurate answers with inline citations.', '<h2>What is Perplexity AI?</h2><p>Perplexity AI combines the conversational interface of a chatbot with the indexing power of a search engine. When you ask a question, it searches the live web and synthesizes an answer, citing its sources so you can verify the information.</p>'),

('Pi', 'pi-ai', 'https://logo.clearbit.com/inflection.ai', 'https://pi.ai', 'A personal AI designed to be supportive, smart, and empathetic.', 'Pi, created by Inflection AI, is designed to be a supportive and empathetic conversational partner. It excels at emotional intelligence, active listening, and providing thoughtful advice rather than just factual answers.', 'c1000000-0000-0000-0000-000000000006', 'free', 0.00, false, NULL, NULL, NULL, NULL, '{"empathetic_responses": true, "conversational_memory": true, "voice_mode": true}', ARRAY['Incredibly natural voice mode', 'High emotional intelligence', 'Completely free to use'], ARRAY['Not suited for coding or hard logic', 'Shorter, more conversational responses'], 8.2, 8000000, 2023, 'Pi by Inflection AI is a uniquely supportive and empathetic conversational AI designed for personal growth and advice.', '<h2>What is Pi?</h2><p>Pi stands for Personal Intelligence. It was built from the ground up to be a conversational partner rather than a purely utilitarian assistant. It asks follow-up questions, remembers your preferences, and features one of the most realistic voice modes available.</p>'),

-- AI Audio & Music (3개)
('ElevenLabs', 'elevenlabs', 'https://logo.clearbit.com/elevenlabs.io', 'https://elevenlabs.io', 'The industry standard for lifelike AI voice generation and text-to-speech.', 'ElevenLabs provides the most realistic and expressive AI voices on the market. Used widely by YouTube creators, audiobook publishers, and game developers, it offers incredible text-to-speech, voice cloning, and dubbing capabilities.', 'c1000000-0000-0000-0000-000000000007', 'freemium', 5.00, true, NULL, NULL, NULL, NULL, '{"realistic_tts": true, "voice_cloning": true, "ai_dubbing": true, "sfx_generation": true}', ARRAY['Unmatched voice realism', 'Instant voice cloning', 'Very affordable starter tier'], ARRAY['Character limits deplete quickly', 'Commercial rights require paid plan'], 9.5, 42000000, 2022, 'ElevenLabs is the undisputed leader in AI text-to-speech and voice cloning. Get the most realistic AI voices from $5/month.', '<h2>What is ElevenLabs?</h2><p>ElevenLabs produces the most natural-sounding text-to-speech currently available. Its models capture human emotion, intonation, and pacing perfectly. It also features a powerful voice cloning tool that requires only minutes of audio to recreate a completely accurate digital replica.</p>'),

('Murf AI', 'murf-ai', 'https://logo.clearbit.com/murf.ai', 'https://murf.ai', 'Versatile AI voice generator tailored for corporate presentations and e-learning.', 'Murf AI is a voiceover studio that specializes in professional, studio-quality voices. It features an intuitive timeline editor where you can sync generated voices with video, background music, and presentations.', 'c1000000-0000-0000-0000-000000000007', 'paid', 29.00, true, NULL, NULL, NULL, NULL, '{"studio_voices": true, "timeline_editor": true, "video_sync": true, "team_collaboration": true}', ARRAY['Great for professional/corporate use', 'Built-in video and audio sync', 'Robust team collaboration tools'], ARRAY['Less emotional range than ElevenLabs', 'Higher starting price point', 'Free plan does not allow downloads'], 8.3, 3500000, 2020, 'Murf AI is a professional voice generator perfect for e-learning, presentations, and corporate videos. Includes a full timeline editor.', '<h2>What is Murf AI?</h2><p>Murf AI is an all-in-one voiceover studio. Rather than just generating audio files, Murf provides a workspace where you can type your script, choose a professional voice, adjust pacing and pitch, and sync the audio directly to your video or slides.</p>'),

('PlayHT', 'playht', 'https://logo.clearbit.com/play.ht', 'https://play.ht', 'Enterprise-grade AI voice generator and text-to-speech API.', 'PlayHT offers ultra-realistic text-to-speech voices with a focus on enterprise scalability and podcast automation. It provides a vast library of voices and an excellent API for integrating voice generation into your own applications.', 'c1000000-0000-0000-0000-000000000007', 'freemium', 39.00, true, NULL, NULL, NULL, NULL, '{"podcast_hosting": true, "api_access": true, "voice_cloning": true, "story_voices": true}', ARRAY['High-quality dynamic voices', 'Excellent API documentation', 'Built-in audio player widgets'], ARRAY['Expensive monthly subscriptions', 'Interface can be slightly complex'], 8.1, 2800000, 2016, 'PlayHT offers premium AI voice generation and text-to-speech API services, ideal for audiobooks and enterprise applications.', '<h2>What is PlayHT?</h2><p>PlayHT is a comprehensive text-to-speech platform that excels in long-form content creation. It provides tools for podcast hosting and includes audio player widgets that bloggers can embed directly into their websites to offer audio versions of their articles.</p>'),

-- AI Writing (2개)
('Anyword', 'anyword', 'https://logo.clearbit.com/anyword.com', 'https://anyword.com', 'Data-driven AI writing platform that predicts content performance.', 'Anyword is an AI copywriting tool uniquely focused on performance marketing. Before you publish, it provides a predictive performance score, estimating how well your ad copy or social media post will convert based on vast marketing datasets.', 'c1000000-0000-0000-0000-000000000001', 'paid', 49.00, true, NULL, NULL, NULL, NULL, '{"predictive_scoring": true, "ad_copy": true, "brand_voice": true, "ab_testing": true}', ARRAY['Data-backed predictive scoring', 'Excellent for performance marketers', 'Connects to your ad accounts'], ARRAY['High starting price', 'No free text generation plan', 'Specialized purely for marketing'], 8.4, 2100000, 2013, 'Anyword is an AI copywriting tool that predicts the performance and conversion rate of your ad copy before you publish it.', '<h2>What is Anyword?</h2><p>Anyword is not just an AI text generator; it is a data-driven copywriting platform. It uses predictive analytics to score generated variations of ad copy, telling marketers which version is statistically most likely to drive clicks and conversions.</p>'),

('Moonbeam', 'moonbeam', 'https://logo.clearbit.com/gomoonbeam.com', 'https://gomoonbeam.com', 'Long-form AI writing assistant designed specifically to beat writer''s block.', 'Moonbeam is an AI writing assistant tailored for writing essays, blogs, and extremely long-form content. Its unique "Wizard" feature takes a simple prompt and expands it into an outline, then a full draft, guiding the user step-by-step.', 'c1000000-0000-0000-0000-000000000001', 'freemium', 15.00, true, NULL, NULL, NULL, NULL, '{"outline_wizard": true, "custom_style": true, "smart_chat": true}', ARRAY['Perfect for long-form essays', 'Very affordable Pro plan', 'Clean, distraction-free editor'], ARRAY['Smaller user base', 'Fewer templates than Jasper', 'Less integration with marketing tools'], 7.9, 150000, 2022, 'Moonbeam is an AI writing assistant that specializes in structuring and writing long-form essays and blogs using its step-by-step Wizard.', '<h2>What is Moonbeam?</h2><p>Moonbeam helps writers tackle long-form content by breaking down the drafting process. Instead of staring at a blank page, you give the Wizard a topic, it generates an editable outline, and then systematically fills out each section based on your feedback.</p>')

ON CONFLICT (slug) DO NOTHING;
