-- ============================================================
-- AIToolRadar Phase 6: 도구 200개 달성을 위한 확장 데이터 (Part 2/3)
-- 10 Tools (Coding, Video, Image, Chatbots)
-- ============================================================

INSERT INTO ai_tools (name, slug, logo_url, website_url, short_description, long_description, category_id, pricing_model, starting_price, has_free_trial, affiliate_url, affiliate_program, commission_type, commission_rate, features, pros, cons, rating, monthly_visits, founded_year, meta_description, content_html) VALUES

-- AI Coding (3개)
('Windsurf', 'windsurf', 'https://logo.clearbit.com/codeium.com', 'https://codeium.com/windsurf', 'The highly-performant AI IDE built by Codeium for agentic coding.', 'Windsurf breaks the boundary between AI assistants and code editors. Built by the Codeium team, it acts as an agentic IDE where the AI natively understands your context and writes code autonomously, accelerating complex workflows.', 'c1000000-0000-0000-0000-000000000003', 'freemium', 15.00, true, NULL, NULL, NULL, NULL, '{"agentic_coding": true, "context_awareness": true, "terminal_integration": true}', ARRAY['Exceptional agentic capabilities', 'Very fast performance', 'Deep codebase understanding'], ARRAY['Newer IDE compared to Cursor', 'Learning curve for agentic flows'], 8.9, 1200000, 2024, 'Windsurf IDE by Codeium offers agentic AI coding capabilities that go far beyond standard autocomplete.', '<h2>What is Windsurf?</h2><p>Windsurf is a next-generation AI IDE that functions as an autonomous coding agent. Rather than just suggesting lines of code, the AI developer inside Windsurf understands your intent and executes complex multi-file edits automatically.</p>'),

('Aider', 'aider', 'https://logo.clearbit.com/aider.chat', 'https://aider.chat', 'Open-source command line AI pair programming tool.', 'Aider is an open-source terminal-based AI pair programmer that lets you work with local large language models or commercial APIs (like GPT-4 and Claude 3.5 Sonnet) directly in your git repository.', 'c1000000-0000-0000-0000-000000000003', 'free', 0.00, false, NULL, NULL, NULL, NULL, '{"command_line": true, "git_integration": true, "bring_your_own_key": true}', ARRAY['Completely free (BYOK)', 'Perfect git integration', 'Very lightweight and fast'], ARRAY['Command line only UI', 'Requires technical setup', 'You pay for your own API key usage'], 8.7, 450000, 2023, 'Aider is a popular open-source command line AI pair programmer that lets you code using models like Claude 3.5 directly in terminal.', '<h2>What is Aider?</h2><p>Aider is an AI pair programming tool that lives entirely in your terminal. It''s designed for power users who want maximum control, letting you connect to APIs like OpenAI to edit code and auto-commit changes.</p>'),

('Codeium', 'codeium', 'https://logo.clearbit.com/codeium.com', 'https://codeium.com', 'Free AI code completion and chat tool offering incredible value for developers.', 'Codeium is the leading free generative AI toolkit for developers. It provides intelligent autocomplete and chat functionality directly inside over 40 editors, with a generous free tier that rivals paid competitors.', 'c1000000-0000-0000-0000-000000000003', 'freemium', 0.00, true, NULL, NULL, NULL, NULL, '{"code_completion": true, "in_editor_chat": true, "40_plus_editors": true}', ARRAY['Incredible free tier', 'Supports virtually every IDE', 'Very low latency'], ARRAY['Enterprise features cost extra', 'Chat slightly less capable than top models'], 8.8, 5500000, 2022, 'Codeium offers free AI code completion and chat across 40+ IDEs. It is widely considered the best free alternative to GitHub Copilot.', '<h2>What is Codeium?</h2><p>Codeium provides AI superpowers to developers for free. Through their extension, you get lightning-fast code autocomplete and a chat interface that understands the context of your currently open files.</p>'),

-- AI Video (3개)
('Kling AI', 'kling-ai', 'https://logo.clearbit.com/kuaishou.com', 'https://kling.kuaishou.com', 'High-fidelity AI video generation model by Kuaishou, supporting ultra-realistic motion.', 'Kling AI, developed by Kuaishou, is a state-of-the-art text-to-video generation model known for producing incredibly realistic physics, long video generation (up to 2 minutes), and high-resolution outputs.', 'c1000000-0000-0000-0000-000000000004', 'freemium', 5.00, true, NULL, NULL, NULL, NULL, '{"text_to_video": true, "image_to_video": true, "long_generation": true, "realistic_physics": true}', ARRAY['Stunning photorealism', 'Generates longer videos than competitors', 'Very accurate physical dynamics'], ARRAY['Sometimes struggles with complex human interactions', 'Access can be geo-restricted', 'Credits deplete quickly for high-res'], 8.6, 3200000, 2024, 'Kling AI generates hyper-realistic videos from text prompts with accurate physics and motion dynamics, rivaling major industry leaders.', '<h2>What is Kling AI?</h2><p>Kling AI burst onto the scene with its incredibly realistic video generation capabilities. It excels at maintaining physical consistency and generating exceptionally lifelike motion that makes it difficult to distinguish from real footage.</p>'),

('Sora', 'sora', 'https://logo.clearbit.com/openai.com', 'https://openai.com/sora', 'OpenAI''s groundbreaking text-to-video model capable of highly detailed, minute-long videos.', 'Sora represents a massive leap forward in AI video generation by OpenAI. It can create complex scenes with multiple characters, specific types of motion, and accurate details of the subject and background, rendering up to a minute of high-fidelity video.', 'c1000000-0000-0000-0000-000000000004', 'paid', 20.00, false, NULL, NULL, NULL, NULL, '{"complex_scenes": true, "multi_angle": true, "high_consistency": true}', ARRAY['Incredible scene consistency', 'Minute-long generation capability', 'Deep language understanding'], ARRAY['Not fully released to the public yet', 'Has occasional physics hallucinations', 'Expected to be expensive'], 9.5, 45000000, 2024, 'Sora is OpenAI''s revolutionary text-to-video model, rendering highly complex, accurate, and consistent scenes up to 60 seconds long.', '<h2>What is Sora?</h2><p>Sora is an AI video model developed by OpenAI that can generate highly detailed and structurally consistent videos from text prompts. Its ability to handle complex camera movements and character consistency sets a new industry standard.</p>'),

('Viggle AI', 'viggle-ai', 'https://logo.clearbit.com/viggle.ai', 'https://viggle.ai', 'AI video generator specialized in consistent character animation and motion transfer.', 'Viggle AI focuses on generating consistent 3D character animations and transferring motion from one video to any character image. It is extremely popular on social media for creating dance memes and precise character animations.', 'c1000000-0000-0000-0000-000000000004', 'freemium', 9.99, true, NULL, NULL, NULL, NULL, '{"motion_transfer": true, "character_animation": true, "discord_bot": true}', ARRAY['Best tool for motion transfer', 'Hilarious and viral use cases', 'Keeps characters highly consistent'], ARRAY['UI is mostly Discord-based initially', 'Struggles with non-human subjects', 'Resolution can be relatively low'], 8.1, 4800000, 2024, 'Viggle AI specializes in motion transfer and character animation. Animate any photo with the motion from any video instantly.', '<h2>What is Viggle AI?</h2><p>Viggle AI went viral for its ability to take a static image of a character (or person) and apply complex motion—like dancing or running—from a reference video, keeping the character perfectly consistent throughout the animation.</p>'),

-- AI Image (3개)
('Leonardo AI', 'leonardo-ai', 'https://logo.clearbit.com/leonardo.ai', 'https://leonardo.ai', 'A complete AI imaging suite for creators with stunning models and canvas editing.', 'Leonardo AI is a powerful platform for AI art generation that gives users access to multiple finely-tuned models, an infinite canvas for precise editing, and tools for real-time generation and 3D texture mapping.', 'c1000000-0000-0000-0000-000000000002', 'freemium', 10.00, true, NULL, NULL, NULL, NULL, '{"multiple_models": true, "infinite_canvas": true, "realtime_generation": true, "image_guidance": true}', ARRAY['Incredible control over generation', 'Generous daily free tokens', 'Beautiful custom models for gaming assets'], ARRAY['Platform can be overwhelming', 'Steeper learning curve than Midjourney', 'Quality varies wildly between models'], 8.8, 18000000, 2022, 'Leonardo AI is the ultimate AI canvas and generation suite, offering real-time generation and unparalleled control for creators.', '<h2>What is Leonardo AI?</h2><p>Leonardo AI is an expansive AI generation platform targeted at artists, game developers, and designers. With its infinite canvas and real-time canvas tools, it offers significantly more granular control over image creation than simple text-prompt generators.</p>'),

('Ideogram', 'ideogram', 'https://logo.clearbit.com/ideogram.ai', 'https://ideogram.ai', 'The undisputed leader in generating accurate text within AI images.', 'Ideogram AI specializes in solving one of generative AI''s biggest problems: spelling. It consistently renders accurate text on signs, logos, and typography while producing highly stylized and photorealistic images.', 'c1000000-0000-0000-0000-000000000002', 'freemium', 8.00, true, NULL, NULL, NULL, NULL, '{"text_rendering": true, "typography": true, "logo_generation": true, "poster_design": true}', ARRAY['Best-in-class text rendering', 'Excellent for posters and logos', 'Easy to use web interface'], ARRAY['Less stylistic range than Midjourney', 'Struggles with highly complex scenes', 'Free tier can have slow generation queues'], 8.7, 12000000, 2023, 'Ideogram is the premier AI image generator for typography and text rendering, making it perfect for logos, posters, and designs with words.', '<h2>What is Ideogram?</h2><p>Ideogram AI was built to excel where other models fail: generating coherent, correctly spelled text inside images. If you need to generate a logo, a neon sign, or a graphic poster with specific phrasing, Ideogram is the tool of choice.</p>'),

('Magnific AI', 'magnific-ai', 'https://logo.clearbit.com/magnific.ai', 'https://magnific.ai', 'Magical AI image upscaler and enhancer that adds unbelievable high-resolution detail.', 'Magnific AI reimagines image upscaling. Rather than just increasing pixel count, it uses AI to hallucinate and add plausible high-resolution details, transforming low-res, artificial, or blurry images into stunningly detailed 4K masterpieces.', 'c1000000-0000-0000-0000-000000000002', 'paid', 39.00, false, NULL, NULL, NULL, NULL, '{"ai_upscaling": true, "detail_enhancement": true, "style_transfer": true}', ARRAY['Unmatched detail enhancement', 'Transforms flat renders into photorealism', 'Incredible for portraits and architecture'], ARRAY['Very expensive pricing', 'Can alter the original image too much', 'No free tier available'], 8.9, 3500000, 2023, 'Magnific AI does not just upscale images; it completely hallucinates high-resolution details, turning basic images into 4K masterpieces.', '<h2>What is Magnific AI?</h2><p>Magnific AI is a premium tool for the final step of the creative process. It acts as an "imaginative" upscaler that adds pores to skin, textures to walls, and intricate details to landscapes, elevating standard AI generations to cinematic quality.</p>'),

-- AI Chatbots (1개)
('Groq', 'groq', 'https://logo.clearbit.com/groq.com', 'https://groq.com', 'Lightning-fast AI inference platform providing the lowest latency chatbot experience.', 'Groq uses its proprietary LPU (Language Processing Unit) architecture to run open-weight models like Llama 3 and Mixtral at mind-bending speeds, generating hundreds of tokens per second for near-instant responses.', 'c1000000-0000-0000-0000-000000000006', 'freemium', 0.00, true, NULL, NULL, NULL, NULL, '{"ultra_low_latency": true, "lpu_hardware": true, "open_models": true}', ARRAY['Instantaneous generation speed', 'Great free tier for API developers', 'Showcases the power of open models'], ARRAY['Runs existing models rather than its own', 'UI is barebones', 'Context windows can be limited based on load'], 8.5, 6000000, 2016, 'Groq delivers the world''s fastest AI inference. Chat with open models like Llama 3 at hundreds of tokens per second.', '<h2>What is Groq?</h2><p>Groq is fundamentally a hardware company that built LPUs (Language Processing Units) specifically for AI inference. Their chat interface serves as a demonstration of this speed, allowing you to interact with models like Meta''s Llama 3 with almost zero latency.</p>')

ON CONFLICT (slug) DO NOTHING;
