-- AIToolRadar Workflows SQL Update
-- Update existing 15 workflows
UPDATE workflows
SET steps = '[{"goal":"Keyword Research & Script Writing","step":1,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Frase","slug":"frase"}],"description":"<strong>Use ChatGPT or Frase</strong> to find high-volume niche keywords.<br><br><strong>Prompt:</strong> ''Act as a YouTube strategist. Write a 10-min hook-driven script on [topic].''<br><br>💡 <strong>Pro tip:</strong> Frase helps analyze competitors. Paid ChatGPT Plus is recommended for deeper web search."},{"goal":"AI Voiceover Generation","step":2,"tools":[{"name":"ElevenLabs","slug":"elevenlabs"}],"description":"Log into <strong>ElevenLabs</strong>, select ''Speech Synthesis'', and pick an engaging voice. Paste your script and tweak stability for natural pauses.<br><br>💡 <strong>Pro tip:</strong> Use the <em>''Eleven Multilingual v2''</em> model for lifelike expression. Free tier gives 10k chars/month."},{"goal":"AI Avatar Video Generation","step":3,"tools":[{"name":"Synthesia","slug":"synthesia"},{"name":"HeyGen","slug":"heygen"}],"description":"Upload your audio to <strong>Synthesia</strong> or <strong>HeyGen</strong>. Choose a dynamic avatar and match the background to your topic.<br><br>💡 <strong>Pro tip:</strong> HeyGen offers ultra-realistic lip-sync. A paid plan is required to remove watermarks and unlock custom avatars."},{"goal":"Video Editing & Auto Captions","step":4,"tools":[{"name":"Descript","slug":"descript"}],"description":"Import the avatar clip into <strong>Descript</strong>. It auto-transcribes everything; simply edit the video by deleting text! Add dynamic captions.<br><br>💡 <strong>Pro tip:</strong> Descript''s <em>''Studio Sound''</em> feature removes background noise magically. Paid tier enables 4K exports."},{"goal":"Short Clips & SEO Optimization","step":5,"tools":[{"name":"Opus Clip","slug":"opus-clip"},{"name":"Surfer SEO","slug":"surfer-seo"}],"description":"Drop your final video into <strong>Opus Clip</strong> to auto-generate viral shorts with flashy captions. Use <strong>Surfer SEO</strong> to optimize your YouTube title.<br><br>💡 <strong>Pro tip:</strong> Opus Clip’s virality score suggests which short to post first on YouTube Shorts."}]'::jsonb
WHERE slug = 'ai-youtube-video-creation';

UPDATE workflows
SET steps = '[{"goal":"Episode Research & Script Writing","step":1,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Claude AI","slug":"claude-ai"}],"description":"Ask <strong>ChatGPT</strong> or <strong>Claude AI</strong>: <em>''Act as a podcast producer. Outline a 30-min engaging episode about [topic] with an intense hook and 3 segments.''</em><br><br>💡 <strong>Pro tip:</strong> Claude AI is great for natural, conversational tones. The free tier is usually sufficient."},{"goal":"AI Voiceover & Narration","step":2,"tools":[{"name":"ElevenLabs","slug":"elevenlabs"},{"name":"Murf AI","slug":"murf-ai"}],"description":"Use <strong>ElevenLabs</strong> or <strong>Murf AI</strong> for narration. For conversational podcasts, generate two distinct voices and splice them.<br><br>💡 <strong>Pro tip:</strong> Murf AI provides robust pitch and emphasis controls ideal for storytelling. A paid plan allows commercial use."},{"goal":"Background Music Generation","step":3,"tools":[{"name":"Suno AI","slug":"suno-ai"},{"name":"Beatoven AI","slug":"beatoven-ai"}],"description":"Generate original intro/outro music using <strong>Suno AI</strong> or <strong>Beatoven AI</strong>. Just prompt: <em>''Upbeat lo-fi intro for a tech podcast.''</em><br><br>💡 <strong>Pro tip:</strong> Beatoven AI allows you to dynamically change the mood mid-track to match your podcast''s energy flow."},{"goal":"Audio Editing & Noise Removal","step":4,"tools":[{"name":"Descript","slug":"descript"}],"description":"Bring your audio tracks into <strong>Descript</strong> for multi-track editing. Remove filler words (ums, uhs) with a single click.<br><br>💡 <strong>Pro tip:</strong> Descript''s text-based editing cuts down production time by 80%. Consider the paid plan for more transcription hours."},{"goal":"Short Clips & Social Promotion","step":5,"tools":[{"name":"Opus Clip","slug":"opus-clip"},{"name":"Canva AI","slug":"canva"}],"description":"Import the final audio into <strong>Opus Clip</strong> or use <strong>Canva AI</strong> to create audiograms with moving waveforms.<br><br>💡 <strong>Pro tip:</strong> Visual podcasts get 3x more engagement on social media. Post these snippets on TikTok and Instagram Reels to drive traffic."}]'::jsonb
WHERE slug = 'ai-podcast-production-workflow';

UPDATE workflows
SET steps = '[{"goal":"Curriculum Design & Script Writing","step":1,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Claude AI","slug":"claude-ai"}],"description":"Use <strong>ChatGPT</strong> to outline course modules. Prompt: <em>''Act as an instructional designer. Outline a 5-module course on [subject] with learning objectives.''</em><br><br>💡 <strong>Pro tip:</strong> Claude AI tends to structure long-form educational content slightly better."},{"goal":"Auto-Generate Lecture Slides","step":2,"tools":[{"name":"Gamma","slug":"gamma"},{"name":"Beautiful.ai","slug":"beautiful-ai"}],"description":"Paste your module outline into <strong>Gamma</strong> or <strong>Beautiful.ai</strong> to instantly generate stunning presentation slide decks.<br><br>💡 <strong>Pro tip:</strong> Gamma''s <em>''Generate from Document''</em> feature can turn a massive text file into a 50-slide deck in under two minutes."},{"goal":"AI Avatar Lecture Videos","step":3,"tools":[{"name":"Synthesia","slug":"synthesia"},{"name":"HeyGen","slug":"heygen"}],"description":"Record lecture videos using <strong>Synthesia</strong> or <strong>HeyGen</strong> by pasting your slide notes as a script for the AI avatar.<br><br>💡 <strong>Pro tip:</strong> Use the picture-in-picture mode so the AI avatar appears in the corner while your slides take up the main screen focus."},{"goal":"Voiceover & Audio Editing","step":4,"tools":[{"name":"ElevenLabs","slug":"elevenlabs"},{"name":"Descript","slug":"descript"}],"description":"Refine the audio with <strong>ElevenLabs</strong> for clear voiceovers, and edit out mistakes using <strong>Descript''s</strong> text editor.<br><br>💡 <strong>Pro tip:</strong> You can fix flubbed words in Descript simply by typing the correct word over the transcript—the AI generates the new audio!"},{"goal":"Promo Video & Thumbnail","step":5,"tools":[{"name":"Canva AI","slug":"canva"},{"name":"InVideo AI","slug":"invideo-ai"}],"description":"Design your course mockups and promotional thumbnails using <strong>Canva AI</strong> or generate stunning visuals with <strong>InVideo AI</strong>.<br><br>💡 <strong>Pro tip:</strong> 3D box mockups of your course in Canva drastically increase the perceived value on your sales landing page."}]'::jsonb
WHERE slug = 'ai-online-course-creation';

UPDATE workflows
SET steps = '[{"goal":"Keyword Research & Competitor Analysis","step":1,"tools":[{"name":"Semrush","slug":"semrush"},{"name":"Frase","slug":"frase"}],"description":"Find low-competition keywords using <strong>Semrush</strong>, then use <strong>Frase</strong> to gather the top 10 ranking outlines.<br><br>💡 <strong>Pro tip:</strong> Frase highlights topic gaps your competitors missed, allowing you to create the most comprehensive guide available."},{"goal":"Outline & First Draft","step":2,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Writesonic","slug":"writesonic"}],"description":"Ask <strong>ChatGPT</strong> or <strong>Writesonic</strong> to draft sections. Prompt: <em>''Write a comprehensive 500-word section on [sub-topic] using natural NLP terms.''</em><br><br>💡 <strong>Pro tip:</strong> Writesonic can browse real-time data, making it ideal for up-to-date factual articles."},{"goal":"SEO Score Optimization","step":3,"tools":[{"name":"Surfer SEO","slug":"surfer-seo"}],"description":"Paste your draft into <strong>Surfer SEO</strong> and add recommended terms until your content score hits 80+.<br><br>💡 <strong>Pro tip:</strong> Don''t forcefully keyword stuff. The goal is to naturally answer the user query while hitting Surfer''s LSI keyword recommendations."},{"goal":"Grammar & Readability Check","step":4,"tools":[{"name":"Grammarly","slug":"grammarly"}],"description":"Run the final text through <strong>Grammarly</strong> to fix tone, passive voice, and complex sentences.<br><br>💡 <strong>Pro tip:</strong> Aim for an 8th-grade reading level. Shorter sentences improve readability on mobile devices and reduce your page bounce rate."},{"goal":"Cover Image Generation","step":5,"tools":[{"name":"Canva AI","slug":"canva"},{"name":"Adobe Firefly","slug":"adobe-firefly"}],"description":"Generate custom, copyright-free blog header images using <strong>Adobe Firefly</strong> or <strong>Canva AI</strong>. Prompt Firefly: <em>''Minimalist flat vector illustration of [topic].''</em><br><br>💡 <strong>Pro tip:</strong> Custom images rank better in Google Images compared to generic stock photos."}]'::jsonb
WHERE slug = 'ai-seo-blog-content-creation';

UPDATE workflows
SET steps = '[{"goal":"Extract Script from Blog or Video","step":1,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Descript","slug":"descript"}],"description":"Paste your existing blog or video transcript into <strong>ChatGPT</strong> and prompt: <em>''Extract the 5 most valuable insights from this text.''</em><br><br>💡 <strong>Pro tip:</strong> Alternatively, use Descript to instantly pull a text transcript from your old YouTube videos."},{"goal":"Auto-Generate Captions & Hashtags","step":2,"tools":[{"name":"Claude AI","slug":"claude-ai"},{"name":"Copy.ai","slug":"copy-ai"}],"description":"Ask <strong>Claude AI</strong> or <strong>Copy.ai</strong> to rewrite the insights into engaging Twitter threads or LinkedIn posts with relevant emojis.<br><br>💡 <strong>Pro tip:</strong> Claude excels at matching your brand''s specific tone of voice. Copy.ai provides great pre-built social templates."},{"goal":"Image & Carousel Design","step":3,"tools":[{"name":"Canva AI","slug":"canva"},{"name":"Adobe Firefly","slug":"adobe-firefly"}],"description":"Head over to <strong>Canva AI</strong> or use <strong>Adobe Firefly</strong> to rapidly generate background images and apply your brand kit to a carousel template.<br><br>💡 <strong>Pro tip:</strong> Canva''s ''Magic Switch'' lets you resize your carousel for both Instagram and LinkedIn in one click."},{"goal":"Short-Form Video Clips","step":4,"tools":[{"name":"Opus Clip","slug":"opus-clip"},{"name":"InVideo AI","slug":"invideo-ai"}],"description":"If you have video footage, upload it to <strong>Opus Clip</strong> or <strong>InVideo AI</strong> to slice the long-form content into bite-sized 30-second vertical videos.<br><br>💡 <strong>Pro tip:</strong> Always ensure your short clips feature a strong visual hook in the first 3 seconds."},{"goal":"Schedule & Auto-Publish","step":5,"tools":[{"name":"n8n","slug":"n8n"}],"description":"Connect your social accounts in <strong>n8n</strong> and set up a weekly scheduling automation to publish your repurposed content across platforms.<br><br>💡 <strong>Pro tip:</strong> n8n is highly customizable for tech-savvy users and avoids the recurring fees of traditional schedulers."}]'::jsonb
WHERE slug = 'ai-social-media-content-repurposing';

UPDATE workflows
SET steps = '[{"goal":"Product Keyword & Competitor Analysis","step":1,"tools":[{"name":"Semrush","slug":"semrush"},{"name":"Ahrefs","slug":"ahrefs"}],"description":"Analyze competitor product listings using <strong>Ahrefs</strong> or <strong>Semrush</strong> to identify keywords that drive buyer intent (e.g., ''buy'', ''best'', ''cheap'').<br><br>💡 <strong>Pro tip:</strong> Look for long-tail keywords specifically to capture highly qualified traffic with less competition."},{"goal":"AI Product Description Generation","step":2,"tools":[{"name":"Jasper","slug":"jasper"},{"name":"ChatGPT","slug":"chatgpt"}],"description":"Input product specs into <strong>Jasper</strong> or <strong>ChatGPT</strong>. Prompt: <em>''Write a persuasive, sensory-rich product description for [product] focusing on benefits over features.''</em><br><br>💡 <strong>Pro tip:</strong> Jasper’s ''Product Description'' template is highly optimized for direct conversions."},{"goal":"SEO Optimization & Readability","step":3,"tools":[{"name":"Surfer SEO","slug":"surfer-seo"},{"name":"Grammarly","slug":"grammarly"}],"description":"Ensure the text is optimized for search using <strong>Surfer SEO</strong> and flawlessly readable via <strong>Grammarly</strong>.<br><br>💡 <strong>Pro tip:</strong> Break descriptions into bullet points. Most e-commerce buyers skim, so place the biggest emotional benefit in the very first bullet."},{"goal":"Product Image Generation","step":4,"tools":[{"name":"Adobe Firefly","slug":"adobe-firefly"},{"name":"Canva AI","slug":"canva"}],"description":"Create lifestyle context images using <strong>Adobe Firefly</strong>. Upload your plain product photo and prompt: <em>''Place on a marble kitchen counter with sunlight.''</em><br><br>💡 <strong>Pro tip:</strong> Canva AI''s ''Magic Edit'' can also effortlessly swap out plain backgrounds for lifestyle scenes."}]'::jsonb
WHERE slug = 'ai-ecommerce-product-descriptions';

UPDATE workflows
SET steps = '[{"goal":"Lead Discovery & Contact Collection","step":1,"tools":[{"name":"Apollo.io","slug":"apollo-io"},{"name":"Clay","slug":"clay"}],"description":"Extract verified B2B leads from <strong>Apollo.io</strong> or use <strong>Clay</strong> to scrape highly targeted prospects from LinkedIn.<br><br>💡 <strong>Pro tip:</strong> Clay allows you to enrich leads with personalized data points (like recent company news), drastically warming up your cold list."},{"goal":"Personalized Email Sequence Writing","step":2,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Instantly.ai","slug":"instantly-ai"}],"description":"Draft your emails automatically using <strong>ChatGPT</strong> or <strong>Instantly.ai''s</strong> copy generator. Prompt: <em>''Write a cold email to [Role] offering [Service]. Keep it under 100 words.''</em><br><br>💡 <strong>Pro tip:</strong> Use a low-friction call to action like, ''Worth a quick chat?''"},{"goal":"Email Warmup & Send Automation","step":3,"tools":[{"name":"Instantly.ai","slug":"instantly-ai"},{"name":"Smartlead","slug":"smartlead"}],"description":"Upload your leads to <strong>Instantly.ai</strong> or <strong>Smartlead</strong> for automated sending and inbox warmup.<br><br>💡 <strong>Pro tip:</strong> Distribute your sends across 3-5 different secondary domains to protect your primary domain''s sender reputation from spam filters."},{"goal":"Response Analysis & Follow-up Automation","step":4,"tools":[{"name":"Lemlist","slug":"lemlist"},{"name":"n8n","slug":"n8n"}],"description":"Track open rates and set conditional follow-ups in <strong>Lemlist</strong> or sequence automated CRM updates via <strong>n8n</strong>.<br><br>💡 <strong>Pro tip:</strong> Lemlist''s ability to overlay the prospect''s website screenshot inside the email body dramatically boosts reply rates."}]'::jsonb
WHERE slug = 'ai-cold-email-outreach';

UPDATE workflows
SET steps = '[{"goal":"Market Research & Data Collection","step":1,"tools":[{"name":"Perplexity AI","slug":"perplexity-ai"},{"name":"ChatGPT","slug":"chatgpt"}],"description":"Use <strong>Perplexity AI</strong> to pull up-to-date industry stats and <strong>ChatGPT</strong> to structure the narrative arc of the pitch.<br><br>💡 <strong>Pro tip:</strong> Perplexity is exceptional for facts because it cites specific web sources, adding credibility to your pitch deck data."},{"goal":"Auto-Generate Pitch Deck","step":2,"tools":[{"name":"Gamma","slug":"gamma"},{"name":"Tome","slug":"tome"}],"description":"Input the narrative into <strong>Gamma</strong> or <strong>Tome</strong> to instantly generate a branded slide deck.<br><br>💡 <strong>Pro tip:</strong> Tome is fantastic for high-end, minimalist aesthetic mockups. Just type a single sentence prompt, and it builds an incredibly professional structure."},{"goal":"Design Polish & Branding","step":3,"tools":[{"name":"Beautiful.ai","slug":"beautiful-ai"},{"name":"Canva AI","slug":"canva"}],"description":"Refine graphs and apply strict brand guidelines using <strong>Beautiful.ai</strong> or <strong>Canva AI</strong>.<br><br>💡 <strong>Pro tip:</strong> Beautiful.ai''s ''Smart Slides'' automatically re-balance the layout when you add or remove bullet points, saving you hours of manual pixel-pushing."},{"goal":"Presentation Script & Rehearsal","step":4,"tools":[{"name":"Claude AI","slug":"claude-ai"},{"name":"Notion AI","slug":"notion-ai"}],"description":"Practice the pitch using <strong>Notion AI</strong> to summarize talking points or <strong>Claude AI</strong> to roleplay as a skeptical client. Prompt Claude: <em>''Act as a tough CEO. Critique this pitch.''</em><br><br>💡 <strong>Pro tip:</strong> Record your practice run and analyze it for pacing."}]'::jsonb
WHERE slug = 'ai-sales-deck-presentation';

UPDATE workflows
SET steps = '[{"goal":"AI Composition & Music Generation","step":1,"tools":[{"name":"Suno AI","slug":"suno-ai"},{"name":"Udio","slug":"udio"}],"description":"Input a detailed prompt into <strong>Suno AI</strong> or <strong>Udio</strong>: <em>''Create a cinematic synthwave track, 120 BPM, with a triumphant chorus.''</em><br><br>💡 <strong>Pro tip:</strong> Udio often provides higher fidelity audio, while Suno is great for catchy vocal hooks. Both offer free daily credits."},{"goal":"Vocal & Voice Dubbing","step":2,"tools":[{"name":"ElevenLabs","slug":"elevenlabs"},{"name":"Murf AI","slug":"murf-ai"}],"description":"If you need specific vocals, write lyrics and synthesize them through <strong>ElevenLabs</strong> or <strong>Murf AI</strong>.<br><br>💡 <strong>Pro tip:</strong> ElevenLabs'' <em>''Voice to Voice''</em> feature lets you sing the melody yourself and transform it into a professional pop star''s voice flawlessly."},{"goal":"Stem Separation & Remastering","step":3,"tools":[{"name":"LALAL.AI","slug":"lalal-ai"},{"name":"AIVA","slug":"aiva"}],"description":"Use <strong>LALAL.AI</strong> to separate the generated tracks into distinct stems (vocals, drums, bass).<br><br>💡 <strong>Pro tip:</strong> Extracting stems allows you to silence the vocals, giving you a perfect backing instrumental track for your video backgrounds."},{"goal":"Final Mixing & Export","step":4,"tools":[{"name":"Descript","slug":"descript"},{"name":"Soundraw","slug":"soundraw"}],"description":"Drag the stems into <strong>Descript</strong> or a traditional DAW. Use <strong>Soundraw</strong> to layer additional royalty-free beats.<br><br>💡 <strong>Pro tip:</strong> Keep background music tracks at -20dB to -25dB so they don''t overpower your main dialogue in your content."}]'::jsonb
WHERE slug = 'ai-music-production-content-creators';

UPDATE workflows
SET steps = '[{"goal":"Property Description & Marketing Copy","step":1,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Anyword","slug":"anyword"}],"description":"Provide the property specs to <strong>ChatGPT</strong> or <strong>Anyword</strong>. Prompt: <em>''Write an enticing luxury real estate listing highlighting the gourmet kitchen and ocean view.''</em><br><br>💡 <strong>Pro tip:</strong> Anyword provides predictive performance scores on which headline will get more clicks."},{"goal":"Photo Enhancement & Virtual Staging","step":2,"tools":[{"name":"Adobe Firefly","slug":"adobe-firefly"},{"name":"Canva AI","slug":"canva"}],"description":"Upload empty room photos to <strong>Adobe Firefly</strong> or <strong>Canva AI</strong> to magically add realistic modern furniture.<br><br>💡 <strong>Pro tip:</strong> Virtual staging is essentially free with AI and helps buyers visualize the space much better than empty white walls."},{"goal":"Property Video Production","step":3,"tools":[{"name":"InVideo AI","slug":"invideo-ai"},{"name":"HeyGen","slug":"heygen"}],"description":"Compile photos into <strong>InVideo AI</strong> or <strong>HeyGen</strong> to create an automated video walkthrough.<br><br>💡 <strong>Pro tip:</strong> HeyGen allows you to have an AI real estate agent speaking in the corner, giving a personalized touch to standard listing slideshows."},{"goal":"Email & Social Marketing Automation","step":4,"tools":[{"name":"Instantly.ai","slug":"instantly-ai"},{"name":"n8n","slug":"n8n"}],"description":"Automate open house follow-up emails using <strong>Instantly.ai</strong> and connect lead forms to your CRM via <strong>n8n</strong>.<br><br>💡 <strong>Pro tip:</strong> Set up a trigger in n8n to instantly SMS you whenever a high-net-worth lead books a tour through the landing page."}]'::jsonb
WHERE slug = 'ai-real-estate-listing-marketing';

UPDATE workflows
SET steps = '[{"goal":"Content Research & Curation","step":1,"tools":[{"name":"Perplexity AI","slug":"perplexity-ai"},{"name":"ChatGPT","slug":"chatgpt"}],"description":"Use <strong>Perplexity AI</strong> to summarize weekly industry news and <strong>ChatGPT</strong> to curate the top 3 stories. Prompt Perplexity: <em>''Find the top 5 trending tech news articles from this week with sources.''</em><br><br>💡 <strong>Pro tip:</strong> This guarantees completely factual, up-to-date curation."},{"goal":"Newsletter Copy Writing","step":2,"tools":[{"name":"Claude AI","slug":"claude-ai"},{"name":"Jasper","slug":"jasper"}],"description":"Draft the newsletter in your brand''s voice via <strong>Claude AI</strong> or <strong>Jasper</strong>.<br><br>💡 <strong>Pro tip:</strong> Feed Claude your past 3 newsletters and tell it to ''Extract the tone constraints and apply them to this new draft'' to maintain perfect brand consistency."},{"goal":"Design & Layout","step":3,"tools":[{"name":"Canva AI","slug":"canva"},{"name":"Adobe Firefly","slug":"adobe-firefly"}],"description":"Format the content into a visually appealing template using <strong>Canva AI</strong> elements or <strong>Adobe Firefly</strong> graphics.<br><br>💡 <strong>Pro tip:</strong> Keep image file sizes under 100kb so your newsletter loads instantly on mobile devices and avoids Gmail''s promotional tab."},{"goal":"Personalization & A/B Testing","step":4,"tools":[{"name":"Copy.ai","slug":"copy-ai"},{"name":"Grammarly","slug":"grammarly"}],"description":"Run A/B tests on 3 different subject lines generated by <strong>Copy.ai</strong>, checking them in <strong>Grammarly</strong> for punchiness.<br><br>💡 <strong>Pro tip:</strong> The best subject lines evoke curiosity. Keep them under 40 characters so they don''t get cut off on mobile screens."},{"goal":"Send Automation & Analytics","step":5,"tools":[{"name":"n8n","slug":"n8n"},{"name":"Activepieces","slug":"activepieces"}],"description":"Connect your content feeds to <strong>Activepieces</strong> or <strong>n8n</strong> to automatically pull live data and schedule your Mailchimp sends.<br><br>💡 <strong>Pro tip:</strong> Activepieces offers a highly visual, user-friendly drag-and-drop builder for folks who find n8n too complex."}]'::jsonb
WHERE slug = 'ai-newsletter-automation';

UPDATE workflows
SET steps = '[{"goal":"Idea Research & Market Analysis","step":1,"tools":[{"name":"Perplexity AI","slug":"perplexity-ai"},{"name":"ChatGPT","slug":"chatgpt"}],"description":"Analyze Amazon Kindle trends using <strong>Perplexity AI</strong>, then generate chapter outlines using <strong>ChatGPT</strong>. Prompt: <em>''Act as a NYT bestselling author. Outline a 10-chapter non-fiction book on [topic].''</em><br><br>💡 <strong>Pro tip:</strong> Ensure each chapter solves a specific problem."},{"goal":"Outline & Structure Design","step":2,"tools":[{"name":"Claude AI","slug":"claude-ai"},{"name":"Notion AI","slug":"notion-ai"}],"description":"Map out character arcs or detailed section notes in <strong>Notion AI</strong> and use <strong>Claude AI</strong> to expand the ideas.<br><br>💡 <strong>Pro tip:</strong> Claude AI has a massive context window, meaning you can paste your entire 30,000-word draft in it to check for plot holes."},{"goal":"AI-Assisted Writing & Drafting","step":3,"tools":[{"name":"Jasper","slug":"jasper"},{"name":"ChatGPT","slug":"chatgpt"}],"description":"Draft the chapters using <strong>Jasper''s</strong> long-form writing assistant or <strong>ChatGPT</strong>, checking word counts as you go.<br><br>💡 <strong>Pro tip:</strong> Jasper''s ''Boss Mode'' is explicitly designed to keep the AI focused over long documents without losing the narrative thread."},{"goal":"Editing & Proofreading","step":4,"tools":[{"name":"Grammarly","slug":"grammarly"},{"name":"ProWritingAid","slug":"prowritingaid"}],"description":"Polishing is crucial: Run your manuscript through <strong>ProWritingAid</strong> or <strong>Grammarly</strong> to eliminate passive voice and fix dialogue tags.<br><br>💡 <strong>Pro tip:</strong> ProWritingAid''s ''Sticky Sentence'' report is incredible for finding and fixing clunky, hard-to-read paragraphs."},{"goal":"Book Cover Design","step":5,"tools":[{"name":"Canva AI","slug":"canva"},{"name":"Midjourney","slug":"midjourney"}],"description":"Prompt <strong>Midjourney</strong> or <strong>Canva AI</strong> for book covers. Prompt Midjourney: <em>''Minimalist typography book cover, vector art, thriller vibes --ar 2:3''</em>.<br><br>💡 <strong>Pro tip:</strong> Always test your generated book cover as a tiny thumbnail to ensure it pops on Amazon search."}]'::jsonb
WHERE slug = 'ai-book-writing-self-publishing';

UPDATE workflows
SET steps = '[{"goal":"Ad Concept & Script Generation","step":1,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Jasper","slug":"jasper"}],"description":"Use <strong>ChatGPT</strong> or <strong>Jasper</strong> to draft direct-response ad scripts. Prompt: <em>''Write a 30-second Facebook ad script using the PAS framework for [product].''</em><br><br>💡 <strong>Pro tip:</strong> Jasper''s marketing templates are highly tuned for conversion."},{"goal":"AI Video & Avatar Generation","step":2,"tools":[{"name":"HeyGen","slug":"heygen"},{"name":"Synthesia","slug":"synthesia"}],"description":"Bring your winning script to <strong>HeyGen</strong> or <strong>Synthesia</strong> to produce an AI spokesperson video without hiring actors.<br><br>💡 <strong>Pro tip:</strong> HeyGen allows you to clone your own face and voice if you want to be the face of your brand. Paid plan required for cloning."},{"goal":"Video Editing & Auto Captions","step":3,"tools":[{"name":"Descript","slug":"descript"},{"name":"Opus Clip","slug":"opus-clip"}],"description":"Refine the raw avatar footage in <strong>Descript</strong> or <strong>Opus Clip</strong>. Add B-roll overlays to keep the ad visually stimulating.<br><br>💡 <strong>Pro tip:</strong> Ads with dynamic B-roll every 3-5 seconds maintain viewer retention significantly better than static talking heads."},{"goal":"Thumbnail & Visual Assets","step":4,"tools":[{"name":"Canva AI","slug":"canva"},{"name":"Adobe Firefly","slug":"adobe-firefly"}],"description":"Use <strong>Adobe Firefly</strong> or <strong>Canva AI</strong> to generate eye-catching thumbnails and end-screen assets with bright colors and bold text.<br><br>💡 <strong>Pro tip:</strong> High-contrast thumbnails can increase your Ad CTR by up to 30%. Always test 3 different variations."},{"goal":"Creative Variations & A/B Testing","step":5,"tools":[{"name":"InVideo AI","slug":"invideo-ai"},{"name":"Copy.ai","slug":"copy-ai"}],"description":"Leverage <strong>InVideo AI</strong> to rapidly create dimension variations (16:9, 9:16, 1:1) and use <strong>Copy.ai</strong> to spin multiple ad copy descriptions.<br><br>💡 <strong>Pro tip:</strong> Fast A/B testing is key; run your variations on a low budget to find the winning combination."}]'::jsonb
WHERE slug = 'ai-video-ad-creative-production';

UPDATE workflows
SET steps = '[{"goal":"Product Analysis & Hook Writing","step":1,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Claude AI","slug":"claude-ai"}],"description":"Research competitors and use <strong>ChatGPT</strong> or <strong>Claude AI</strong> to write compelling UGC hooks. Prompt: <em>''Write 5 TikTok UGC hooks for a skincare product that stop the scroll.''</em><br><br>💡 <strong>Pro tip:</strong> Claude''s outputs often feel more native and less ''salesy'' for TikTok."},{"goal":"AI Avatar UGC Video Generation","step":2,"tools":[{"name":"HeyGen","slug":"heygen"},{"name":"Synthesia","slug":"synthesia"}],"description":"Use <strong>HeyGen</strong> or <strong>Synthesia</strong> to render realistic avatars delivering your UGC script in a casual, selfie-style format.<br><br>💡 <strong>Pro tip:</strong> Choose an avatar holding a phone or standing in a living room background to make it feel like authentic user-generated content."},{"goal":"Video Editing & Caption Overlay","step":3,"tools":[{"name":"Descript","slug":"descript"},{"name":"Canva AI","slug":"canva"}],"description":"Edit in <strong>Descript</strong> or <strong>Canva AI</strong> to add trending stickers, bold native-looking captions, and rapid jump cuts.<br><br>💡 <strong>Pro tip:</strong> Mimicking the native font of TikTok or Instagram Reels drastically improves watch time compared to highly polished corporate fonts."},{"goal":"Creative Variation & Scaling","step":4,"tools":[{"name":"InVideo AI","slug":"invideo-ai"},{"name":"Copy.ai","slug":"copy-ai"}],"description":"Use <strong>InVideo AI</strong> or <strong>Copy.ai</strong> to generate multiple voiceover variations (energetic vs. calm) for the exact same visual ad.<br><br>💡 <strong>Pro tip:</strong> Even minor changes in audio tone can shift return on ad spend (ROAS). Test variations to see what the audience likes."}]'::jsonb
WHERE slug = 'ai-ugc-ad-creation';

UPDATE workflows
SET steps = '[{"goal":"Persuasive Copy & Headlines","step":1,"tools":[{"name":"ChatGPT","slug":"chatgpt"},{"name":"Jasper","slug":"jasper"}],"description":"Generate conversion-focused copy and headlines using <strong>Jasper</strong> or <strong>ChatGPT</strong>. Prompt: <em>''Write a landing page hero section targeting [audience] with a clear value proposition.''</em><br><br>💡 <strong>Pro tip:</strong> Use the AIDA framework (Attention, Interest, Desire, Action)."},{"goal":"Hero Image & Visual Generation","step":2,"tools":[{"name":"Midjourney","slug":"midjourney"},{"name":"Adobe Firefly","slug":"adobe-firefly"}],"description":"Prompt <strong>Midjourney</strong> or <strong>Adobe Firefly</strong> for high-quality hero assets: <em>''3D isometric tech illustration, clean background, brand colors #0044cc''</em>.<br><br>💡 <strong>Pro tip:</strong> Isolate the background using Canva AI to ensure your images blend perfectly into the webpage."},{"goal":"Page Design & Layout","step":3,"tools":[{"name":"Canva AI","slug":"canva"},{"name":"Beautiful.ai","slug":"beautiful-ai"}],"description":"Assemble the page mockups efficiently using <strong>Beautiful.ai</strong> or <strong>Canva</strong> UI templates.<br><br>💡 <strong>Pro tip:</strong> Canva has thousands of pre-built landing page wireframes; simply replace the dummy text with your AI-generated copy and export the assets."},{"goal":"SEO & Copy Optimization","step":4,"tools":[{"name":"Surfer SEO","slug":"surfer-seo"},{"name":"Grammarly","slug":"grammarly"}],"description":"Optimize the final copy using <strong>Surfer SEO</strong> for organic search ranking and <strong>Grammarly</strong> for punchiness.<br><br>💡 <strong>Pro tip:</strong> Make sure your call-to-action (CTA) button text is action-oriented (e.g., ''Start Building Free'' instead of just ''Submit'')."},{"goal":"Analytics & Conversion Tracking","step":5,"tools":[{"name":"n8n","slug":"n8n"},{"name":"Activepieces","slug":"activepieces"}],"description":"Use <strong>n8n</strong> or <strong>Activepieces</strong> to route form submissions directly to a Google Sheet and trigger auto-responder emails.<br><br>💡 <strong>Pro tip:</strong> Fast response times are vital. Set the n8n logic to ping a Slack channel instantly when a high-value lead submits a form."}]'::jsonb
WHERE slug = 'ai-landing-page-creation';

-- Insert new workflow

INSERT INTO workflows (slug, title, tagline, is_published, description, steps)
VALUES (
  'ai-faceless-tiktok-automation',
  'AI Faceless TikTok Automation',
  'Create a fully automated faceless TikTok channel with AI scripts, voiceovers, and visuals',
  true,
  'Automate a faceless TikTok channel using AI to script, voice, and generate visuals completely hands-off.',
  '[{"step":1,"goal":"Niche Selection & Scripting","description":"Ask <strong>ChatGPT</strong>: <em>''Write 5 viral 30-sec scripts for a faceless TikTok channel about [niche], focusing on hooks.''</em><br><br>💡 <strong>Pro tip:</strong> Use the free ChatGPT, but format outputs into a table so it''s easy to paste into spreadsheets.","tools":[{"name":"ChatGPT","slug":"chatgpt"}]},{"step":2,"goal":"Voiceover Generation","description":"Paste your script into <strong>ElevenLabs</strong> using a mysterious or energetic voice.<br><br>💡 <strong>Pro tip:</strong> The ''Adam'' voice is highly popular for fact-based faceless channels. The free tier gives plenty of characters to test content.","tools":[{"name":"ElevenLabs","slug":"elevenlabs"}]},{"step":3,"goal":"Visuals & Editing","description":"Use <strong>Canva AI</strong> or <strong>Midjourney</strong> to create engaging background images, and assemble them in <strong>CapCut</strong>. Add auto-captions.<br><br>💡 <strong>Pro tip:</strong> Yellow and white bold captions with a slight shadow keep viewers repeatedly watching.","tools":[{"name":"Canva AI","slug":"canva"},{"name":"CapCut","slug":"capcut"}]}]'::jsonb
);
